/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: pki_utility_api.c

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The utility apis for PKI implementation

        *   PKIUtilityInitKeyGenParams
        *   PKIUtilityGetPrivateKeyInfoEncoding

    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        Bin Zhu

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   09/11/2002  initial revision

 **********************************************************************/

#include "ansc_pki_local.h"

/*************************************************************************
 *
 * This is the api to init the KeyGenParams from the given certificate
 * and private key info
 *
 *************************************************************************/
ANSC_STATUS
PKIUtilityInitKeyGenParams
    (
        ANSC_HANDLE                         hSSLCrypto,
        PANSC_ASN1_CERTIFICATE              pCert,
        PANSC_ASN1_PRIVATEKEYINFO           pKeyInfo,
        ANSC_HANDLE                         hKeyGenParams
    )
{
    PANSC_CRYPTO_PUB_KEY_GEN_PARAMS         pKeyGenParams = (PANSC_CRYPTO_PUB_KEY_GEN_PARAMS)hKeyGenParams;
    PANSC_CRYPTO_PUB_SSLEAY_OBJECT          pSSLCrypto    = (PANSC_CRYPTO_PUB_SSLEAY_OBJECT)hSSLCrypto;
    BOOLEAN                                 bKeyPair      = TRUE;
    PKI_KEY_TYPE                            keyType;

    if( pCert == NULL || pKeyInfo == NULL || hKeyGenParams == NULL)
    {
        return ANSC_STATUS_FAILURE;
    }

    keyType = pCert->GetKeyType(pCert);

    if( keyType != PKI_RSA_KEY && keyType != PKI_DSA_KEY)
    {
        return ANSC_STATUS_FAILURE;
    }

    if( keyType != pKeyInfo->GetKeyType(pKeyInfo))
    {
        AnscTrace("The key pair  is not in the same key type.\n");

        return ANSC_STATUS_FAILURE;
    }

    /* init the public key */
    if( ANSC_STATUS_SUCCESS != 
            pCert->ExportPublicKey
                (
                    pCert,
                    hKeyGenParams
                ))
    {
        return ANSC_STATUS_FAILURE;
    }

    /* init the private key */
    if( ANSC_STATUS_SUCCESS !=
            pKeyInfo->ExportKey
                (
                    pKeyInfo,
                    hKeyGenParams
                ))
    {
        return ANSC_STATUS_FAILURE;
    }

    /* verify the key pair */
    if( pSSLCrypto != NULL)
    {
        if( keyType == PKI_RSA_KEY)
        {
            bKeyPair = 
                pSSLCrypto->KeyPairMatch
                    (
                        pSSLCrypto,
                        ANSC_CRYPTO_PUB_KEY_RSA,
                        &pKeyGenParams->PublicKey.RSA,
                        &pKeyGenParams->PrivateKey.RSA
                    );
        }
        else
        {
            bKeyPair = 
                pSSLCrypto->KeyPairMatch
                    (
                        pSSLCrypto,
                        ANSC_CRYPTO_PUB_KEY_DSA,
                        &pKeyGenParams->PublicKey.DSA,
                        &pKeyGenParams->PrivateKey.DSA
                    );
        }
    }

    if( bKeyPair)
    {
        return ANSC_STATUS_SUCCESS;
    }
    else
    {
        return ANSC_STATUS_FAILURE;
    }
}

/*************************************************************************
 *
 * This is the reverse api of above, with the given key type and KeyGenParams,
 * generate the private key info encoding;
 *
 *************************************************************************/
PUCHAR
PKIUtilityGetPrivateKeyInfoEncoding
    (
        ANSC_HANDLE                 hKeyGenParams,
        PKI_KEY_TYPE                keyType,
        PULONG                      pLength
    )
{
    PANSC_ASN1_PRIVATEKEYINFO       pKeyInfo;
    PUCHAR                          pEncoding;

    if( hKeyGenParams == NULL || pLength == NULL)
    {
        return NULL;
    }

    pKeyInfo = (PANSC_ASN1_PRIVATEKEYINFO)
        AnscAsn1CreatePrivateKeyInfo(NULL);

    if( pKeyInfo == NULL)
    {
        return NULL;
    }

    if( !pKeyInfo->InitKey(pKeyInfo, keyType, hKeyGenParams))
    {
        pKeyInfo->AsnFree(pKeyInfo);

        return NULL;
    }

    pEncoding = pKeyInfo->GetEncodedData(pKeyInfo, pLength);

    pKeyInfo->AsnFree(pKeyInfo);

    return pEncoding;
}

