/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: ansc_asn1_CRL_interface.h

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The ASN.1 object defined in this file

        *   ANSC_ASN1_CRL
        *   ANSC_ASN1_TBSCERTLIST
        *   ANSC_ASN1_REVOKEDCERTIFICATE
        *   ANSC_ASN1_REVOKEDCERTIFICATES
        *   ANSC_ASN1_SIGNATURE
        *   ANSC_ASN1_CERTIFICATELIST


    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        ASNMAGIC ANSC CODE GENERATOR 1.0

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   05/07/2002  initial revision

 **********************************************************************/


#ifndef  _ANSC_ASN1_CRL_INTERFACE_H
#define  _ANSC_ASN1_CRL_INTERFACE_H

/**********************************************************************

 OBJECT -- ANSC_ASN1_CRL

 CRL ::= Sequence 
     {
                       tbsCertList TBSCertList 
                 sigatureAlgorithm SignatureAlgorithmIdentifier 
                         signature Signature 
     }

 **********************************************************************/
typedef BOOLEAN
(*PFN_CRL_VERIFY)
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hPublicKey
    );

typedef BOOLEAN
(*PFN_CRL_CERT_REVOKED)
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hSerialNumber
    );

typedef BOOLEAN
(*PFN_CRL_ENUMERATE_REVOKED)
    (
        ANSC_HANDLE                 hThisObject,
        EnumRevokedCertProc         proc,
        PVOID                       pData
    );

typedef SIGNATURE_TYPE
(*PFN_CRL_GET_SIGNATURE_TYPE)
    (
        ANSC_HANDLE                 hThisObject
    );

typedef BOOLEAN
(*PFN_CRL_IS_EXPIRED)
    (
        ANSC_HANDLE                 hThisObject
    );

#define  ANSC_ASN1_CRL_CLASS_CONTENT                                  \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    PUCHAR                          pSignedData;                      \
    ULONG                           uSignedLength;                    \
    PFN_ASN1_GET_CHILD              GetTbsCertList;                   \
    PFN_ASN1_GET_CHILD              GetSigatureAlgorithm;             \
    PFN_ASN1_GET_CHILD              GetSignature;                     \
    PFN_ASN1_GET_CHILD              GetIssuerHandle;                  \
    PFN_ASN1_GET_CHILD              GetThisUpdateTime;                \
    PFN_ASN1_GET_CHILD              GetNextUpdateTime;                \
    PFN_CRL_GET_SIGNATURE_TYPE      GetSignatureType;                 \
    PFN_CRL_VERIFY                  Verify;                           \
    PFN_CRL_CERT_REVOKED            IsCertRevoked;                    \
    PFN_CRL_ENUMERATE_REVOKED       EnumRevokedCert;                  \
    PFN_CRL_IS_EXPIRED              IsCRLExpired;                     \
    /* end of object class content */                                 \


typedef  struct
_ANSC_ASN1_CRL
{
    ANSC_ASN1_CRL_CLASS_CONTENT
}
ANSC_ASN1_CRL,  *PANSC_ASN1_CRL;

#define  ACCESS_ANSC_ASN1_CRL(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_CRL, Linkage)

/**********************************************************************

 OBJECT -- ANSC_ASN1_TBSCERTLIST

 TBSCertList ::= Sequence 
     {
                           version Integer 
                         signature AlgorithmIdentifier 
                            issuer Name 
                        thisUpdate Time 
                        nextUpdate Time 
               revokedCertificates RevokedCertificates 
                     crlExtensions [CON 0] Extensions OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_TBSCERTLIST_CLASS_CONTENT            ANSC_ASN1_SEQUENCE_CLASS_CONTENT

typedef  struct
_ANSC_ASN1_TBSCERTLIST
{
    ANSC_ASN1_TBSCERTLIST_CLASS_CONTENT
}
ANSC_ASN1_TBSCERTLIST,  *PANSC_ASN1_TBSCERTLIST;

#define  ACCESS_ANSC_ASN1_TBSCERTLIST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_TBSCERTLIST, Linkage)

/**********************************************************************

 OBJECT -- ANSC_ASN1_REVOKEDCERTIFICATE

 RevokedCertificate ::= Sequence 
     {
             userCertificateNumber CertificateSerialNumber 
                    revocationDate Time 
                crlEntryExtensions Extensions 
     }

 **********************************************************************/

#define  ANSC_ASN1_REVOKEDCERTIFICATE_CLASS_CONTENT     ANSC_ASN1_SEQUENCE_CLASS_CONTENT

typedef  struct
_ANSC_ASN1_REVOKEDCERTIFICATE
{
    ANSC_ASN1_REVOKEDCERTIFICATE_CLASS_CONTENT
}
ANSC_ASN1_REVOKEDCERTIFICATE,  *PANSC_ASN1_REVOKEDCERTIFICATE;

#define  ACCESS_ANSC_ASN1_REVOKEDCERTIFICATE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_REVOKEDCERTIFICATE, Linkage)

/**********************************************************************

 OBJECT -- ANSC_ASN1_REVOKEDCERTIFICATES

 RevokedCertificates ::= SequenceOf RevokedCertificate  {}

 **********************************************************************/

typedef  ANSC_ASN1_SEQUENCEOF ANSC_ASN1_REVOKEDCERTIFICATES,    \
         *PANSC_ASN1_REVOKEDCERTIFICATES;

#define  ACCESS_ANSC_ASN1_REVOKEDCERTIFICATES(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_REVOKEDCERTIFICATES, Linkage)

/**********************************************************************

 OBJECT -- ANSC_ASN1_SIGNATURE

 Signature ::= BitString 

 **********************************************************************/

typedef  ANSC_ASN1_BITSTRING ANSC_ASN1_SIGNATURE,    \
         *PANSC_ASN1_SIGNATURE;

#define  ACCESS_ANSC_ASN1_SIGNATURE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SIGNATURE, Linkage)

/**********************************************************************

 OBJECT -- ANSC_ASN1_CERTIFICATELIST

 CertificateList ::= CRL 

 **********************************************************************/

typedef  ANSC_ASN1_CRL ANSC_ASN1_CERTIFICATELIST,    \
         *PANSC_ASN1_CERTIFICATELIST;

#define  ACCESS_ANSC_ASN1_CERTIFICATELIST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_CERTIFICATELIST, Linkage)


#endif  /*_ANSC_ASN1_CRL_INTERFACE_H*/


