/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: ansc_asn1_othername_export_api.h

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The Internal functions defined for ASN.1 objects

        *   ANSC_ASN1_OTHERNAME
        *   ANSC_ASN1_OTHERSTRING


    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        ASNMAGIC ANSC CODE GENERATOR 1.0

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   07/25/2002  initial revision

 **********************************************************************/


#ifndef  _ANSC_ASN1_OTHERNAME_EXPORTED_API_H
#define  _ANSC_ASN1_OTHERNAME_EXPORTED_API_H

/**********************************************************************

 OBJECT -- ANSC_ASN1_OTHERNAME

 OtherName ::= Sequence 
     {
                                id OID 
                             other [CON 0] OtherString 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateOtherName
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_OTHERSTRING

 OtherString ::= Choice 
     {
                          kerberos KerberosName 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateOtherString
    (
        ANSC_HANDLE                 hReserved
    );


#endif  /*_ANSC_ASN1_OTHERNAME_EXPORTED_API_H*/


