/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: ansc_asn1_ContentInfo_export_api.h

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The Internal functions defined for ASN.1 objects

        *   ANSC_ASN1_CONTENTINFO
        *   ANSC_ASN1_DATA
        *   ANSC_ASN1_SIGNEDDATA
        *   ANSC_ASN1_DIGESTALGORITHMIDENTIFIERS
        *   ANSC_ASN1_CERTIFICATES
        *   ANSC_ASN1_CERTIFICATEREVOCATIONLISTS
        *   ANSC_ASN1_SIGNERINFOS
        *   ANSC_ASN1_SIGNERINFO
        *   ANSC_ASN1_ISSUERANDSERIALNUMBER
        *   ANSC_ASN1_DIGESTENCRYPTIONALGORITHMIDENTIFIER
        *   ANSC_ASN1_ENCRYPTEDDIGEST
        *   ANSC_ASN1_DIGESTINFO
        *   ANSC_ASN1_ENVELOPEDDATA
        *   ANSC_ASN1_RECIPIENTINFOS
        *   ANSC_ASN1_ENCRYPTEDCONTENTINFO
        *   ANSC_ASN1_RECIPIENTINFO
        *   ANSC_ASN1_ENCRYPTEDCONTENT
        *   ANSC_ASN1_PKCS7ENCRYPTEDKEY
        *   ANSC_ASN1_SIGNEDANDENVELOPEDDATA
        *   ANSC_ASN1_DIGESTEDDATA
        *   ANSC_ASN1_DIGEST
        *   ANSC_ASN1_ENCRYPTEDDATA
        *   ANSC_ASN1_CONTENTDATA


    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        ASNMAGIC ANSC CODE GENERATOR 1.0

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   05/07/2002  initial revision

 **********************************************************************/


#ifndef  _ANSC_ASN1_CONTENTINFO_EXPORTED_API_H
#define  _ANSC_ASN1_CONTENTINFO_EXPORTED_API_H

/**********************************************************************

 OBJECT -- ANSC_ASN1_CONTENTINFO

 ContentInfo ::= Sequence 
     {
                       contentType OID 
                           content [CON 0] ContentData OPT
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateContentInfo
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_DATA

 Data ::= OctetString 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateData
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_SIGNEDDATA

 SignedData ::= Sequence 
     {
                           version Integer 
                  digestAlgorithms DigestAlgorithmIdentifiers 
                       contentInfo ContentInfo 
                      certificates [CON 0] IMP Certificates OPT
                              crls [CON 1] IMP CertificateRevocationLists OPT
                       signerInfos SignerInfos 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateSignedData
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_DIGESTALGORITHMIDENTIFIERS

 DigestAlgorithmIdentifiers ::= SetOf DigestAlgorithmIdentifier  {}

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDigestAlgorithmIdentifiers
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_CERTIFICATES

 Certificates ::= SetOf Certificate  {}

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateCertificates
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_CERTIFICATEREVOCATIONLISTS

 CertificateRevocationLists ::= SetOf CRL  {}

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateCertificateRevocationLists
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_SIGNERINFOS

 SignerInfos ::= SetOf SignerInfo  {}

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateSignerInfos
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_SIGNERINFO

 SignerInfo ::= Sequence 
     {
                           version Integer 
             issuerAndSerialNumber IssuerAndSerialNumber 
                   digestAlgorithm DigestAlgorithmIdentifier 
           authenticatedAttributes [CON 0] IMP Attributes OPT
         digestEncryptionAlgorithm DigestEncryptionAlgorithmIdentifier 
                   encryptedDigest EncryptedDigest 
         unauthenticatedAttributes [CON 1] IMP Attributes OPT
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateSignerInfo
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_ISSUERANDSERIALNUMBER

 IssuerAndSerialNumber ::= Sequence 
     {
                            issuer Name 
                      serialNumber Integer 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateIssuerAndSerialNumber
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_DIGESTENCRYPTIONALGORITHMIDENTIFIER

 DigestEncryptionAlgorithmIdentifier ::= AlgorithmIdentifier 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDigestEncryptionAlgorithmIdentifier
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_ENCRYPTEDDIGEST

 EncryptedDigest ::= OctetString 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateEncryptedDigest
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_DIGESTINFO

 DigestInfo ::= Sequence 
     {
                         digestAlg DigestAlgorithmIdentifier 
                            digest OctetString 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDigestInfo
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_ENVELOPEDDATA

 EnvelopedData ::= Sequence 
     {
                           version Integer 
                    recipientInfos RecipientInfos 
              encryptedContentInfo EncryptedContentInfo 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateEnvelopedData
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_RECIPIENTINFOS

 RecipientInfos ::= SetOf RecipientInfo  {}

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateRecipientInfos
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_ENCRYPTEDCONTENTINFO

 EncryptedContentInfo ::= Sequence 
     {
                       contentType OID 
        contentEncryptionAlgorithm EncryptionAlgorithmIdentifier 
                           content [CON 0] IMP EncryptedContent OPT
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateEncryptedContentInfo
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_RECIPIENTINFO

 RecipientInfo ::= Sequence 
     {
                           version Integer 
              issuerAndSerialNumer IssuerAndSerialNumber 
            keyEncryptionAlgorithm EncryptionAlgorithmIdentifier 
                      encryptedKey PKCS7EncryptedKey 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateRecipientInfo
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_ENCRYPTEDCONTENT

 EncryptedContent ::= OctetString 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateEncryptedContent
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_PKCS7ENCRYPTEDKEY

 PKCS7EncryptedKey ::= OctetString 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreatePKCS7EncryptedKey
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_SIGNEDANDENVELOPEDDATA

 SignedAndEnvelopedData ::= Sequence 
     {
                           version Integer 
                    recipientInfos RecipientInfos 
                  digestAlgorithms DigestAlgorithmIdentifiers 
              encryptedContentInfo EncryptedContentInfo 
                      certificates [CON 0] IMP Certificates OPT
                              crls [CON 1] IMP CertificateRevocationLists OPT
                       signerInfos SignerInfos 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateSignedAndEnvelopedData
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_DIGESTEDDATA

 DigestedData ::= Sequence 
     {
                           version Integer 
                   digestAlgorithm DigestAlgorithmIdentifier 
                       contentInfo ContentInfo 
                            digest Digest 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDigestedData
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_DIGEST

 Digest ::= OctetString 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDigest
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_ENCRYPTEDDATA

 EncryptedData ::= Sequence 
     {
                           version Integer 
              encryptedContentInfo EncryptedContentInfo 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateEncryptedData
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_CONTENTDATA

 ContentData ::= Choice 
     {
                              data Data 
                        signedData SignedData 
                      envelopeData EnvelopedData 
            signedAndEnvelopedData SignedAndEnvelopedData 
                        digestData DigestedData 
                     encryptedData EncryptedData 
                          authPack AuthPack 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateContentData
    (
        ANSC_HANDLE                 hReserved
    );


#endif  /*_ANSC_ASN1_CONTENTINFO_EXPORTED_API_H*/


