/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: ansc_asn1_CertificateRequest_export_api.h

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The Internal functions defined for ASN.1 objects

        *   ANSC_ASN1_CERTIFICATEREQUEST
        *   ANSC_ASN1_CERTIFICATIONREQUESTINFO


    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        ASNMAGIC ANSC CODE GENERATOR 1.0

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   04/29/2002  initial revision

 **********************************************************************/


#ifndef  _ANSC_ASN1_CERTIFICATEREQUEST_EXPORTED_API_H
#define  _ANSC_ASN1_CERTIFICATEREQUEST_EXPORTED_API_H

/**********************************************************************

 OBJECT -- ANSC_ASN1_CERTIFICATEREQUEST

 CertificateRequest ::= Sequence 
     {
            certificateRequestInfo CertificationRequestInfo 
      signatureAlgorithmIdentifier SignatureAlgorithmIdentifier 
                         signature BitString 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateCertificateRequest
    (
        ANSC_HANDLE                 hReserved
    );

ANSC_HANDLE
AnscAsn1GeneratePKCS10Request
    (
        ANSC_HANDLE                 hReserved,
        PALCERTIFICATE_ATTRIBUTE    pAttrObject,
        ANSC_HANDLE                 hKeyPairHandle
    );

ANSC_HANDLE
AnscAsn1GenPKCS10RequestWithCryptoAPI
    (
        ANSC_HANDLE                 hReserved,
        PALCERTIFICATE_ATTRIBUTE    pAttrObject,
        ANSC_HANDLE                 hCryptoAPI
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_CERTIFICATIONREQUESTINFO

 CertificationRequestInfo ::= Sequence 
     {
                           version Integer 
                           subject Name 
                     subjectPKInfo SubjectPublicKeyInfo 
                        attributes [CON 0] IMP Attributes OPT
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateCertificationRequestInfo
    (
        ANSC_HANDLE                 hReserved
    );


#endif  /*_ANSC_ASN1_CERTIFICATEREQUEST_EXPORTED_API_H*/


