/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: ansc_asn1_PublicKey_export_api.h

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The Internal functions defined for ASN.1 objects

        *   ANSC_ASN1_PUBLICKEY
        *   ANSC_ASN1_RSAPUBLICKEY
        *   ANSC_ASN1_DSAPUBLICKEY
        *   ANSC_ASN1_DHPUBLICKEY

    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        ASNMAGIC ANSC CODE GENERATOR 1.0

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   05/07/2002  initial revision
        *   08/09/2002  encryption functions are added
        *   08/13/2002  dhpublickey is added;

 **********************************************************************/


#ifndef  _ANSC_ASN1_PUBLICKEY_EXPORTED_API_H
#define  _ANSC_ASN1_PUBLICKEY_EXPORTED_API_H

/**********************************************************************

 OBJECT -- ANSC_ASN1_PUBLICKEY

 PublicKey ::= Choice 
     {
                      dsaPublicKey DSAPublicKey 
                      rsaPublicKey RSAPublicKey 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreatePublicKey
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_RSAPUBLICKEY

 RSAPublicKey ::= Sequence 
     {
                           modulus Integer 
                    publicExponent Integer 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateRSAPublicKey
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_DSAPUBLICKEY

 DSAPublicKey ::= Integer 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDSAPublicKey
    (
        ANSC_HANDLE                 hReserved
    );


/**********************************************************************

 OBJECT -- ANSC_ASN1_DHPUBLICKEY

 DHPublicKey ::= Integer 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDHPublicKey
    (
        ANSC_HANDLE                 hReserved
    );

/**********************************************************************

 OBJECT -- ANSC_ASN1_KEYPAIR

 KeyPair ::= Sequence 
     {
                           keyType Integer 
                            pubKey PublicKey
                            priKey PrivateKeyInfo
     }

 **********************************************************************/
ANSC_HANDLE
AnscAsn1CreateKeyPair
    (
        ANSC_HANDLE                 hReserved
    );

#endif  /*_ANSC_ASN1_PUBLICKEY_EXPORTED_API_H*/


