/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: asn1_ldapmessage_interface.h

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The ASN.1 object defined in this file

        *   ASN1_LDAPMESSAGE
        *   ASN1_LDAPPROTOCOL
        *   ASN1_CONTROLS
        *   ASN1_CONTROL
        *   ASN1_LDAPSTRING
        *   ASN1_MATCHINGRULEID
        *   ASN1_LDAPATTRDESCLIST
        *   ASN1_ATTRVALUEASSERTION
        *   ASN1_LDAPATTRSET
        *   ASN1_LDAPATTRIBUTE
        *   ASN1_LDAPRESULT
        *   ASN1_REFERRAL
        *   ASN1_BINDREQUEST
        *   ASN1_AUTHENTICATIONCHOICE
        *   ASN1_SASLCREDENTIALS
        *   ASN1_BINDRESPONSE
        *   ASN1_UNBINDREQUEST
        *   ASN1_SEARCHREQUEST
        *   ASN1_FILTER
        *   ASN1_FILTERS
        *   ASN1_SUBSTRINGFILTER
        *   ASN1_MATCHINGRULEASSERSIOIN
        *   ASN1_SUBSTRINGS
        *   ASN1_SUBSTRINGCHOICE
        *   ASN1_SEARCHRESULTENTRY
        *   ASN1_PARTIALATTRIBUTELIST
        *   ASN1_SEARCHRESULTREFERENCE
        *   ASN1_SEARCHRESULTDONE
        *   ASN1_MODIFYREQUEST
        *   ASN1_MODIFYRESPONSE
        *   ASN1_ADDREQUEST
        *   ASN1_LDAPATTRLIST
        *   ASN1_LDAPATTRTYPEANDVALUES
        *   ASN1_MODIFICATION
        *   ASN1_MODIFICATIONS
        *   ASN1_ADDRESPONSE
        *   ASN1_DELREQUEST
        *   ASN1_DELRESPONSE
        *   ASN1_MODIFYDNREQUESTS
        *   ASN1_MODIFYDNRESPONSE
        *   ASN1_COMPAREREQUEST
        *   ASN1_COMPARERESPONSE
        *   ASN1_ABANDONREQUEST
        *   ASN1_EXTENDEDREQUEST
        *   ASN1_EXTENDEDRESPONSE


    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        ASNMAGIC ANSC CODE GENERATOR 1.0

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   01/26/2006  initial revision

 **********************************************************************/


#ifndef  _ASN1_LDAPMESSAGE_INTERFACE_H
#define  _ASN1_LDAPMESSAGE_INTERFACE_H

/**********************************************************************

 OBJECT -- ASN1_LDAPMESSAGE

 LDAPMessage ::= Sequence 
     {
                         messageID Integer 
                        protocolOp LDAPProtocol 
                          controls [CON 0] IMP Controls 
     }

 **********************************************************************/

#define  ANSC_ASN1_LDAPMESSAGE_CLASS_CONTENT                          \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPMESSAGE
{
    ANSC_ASN1_LDAPMESSAGE_CLASS_CONTENT
}
ANSC_ASN1_LDAPMESSAGE,  *PANSC_ASN1_LDAPMESSAGE;

#define  ACCESS_ANSC_ASN1_LDAPMESSAGE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPMESSAGE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPPROTOCOL

 LDAPProtocol ::= Choice 
     {
                       bindRequest BindRequest 
                      bindResponse BindResponse 
                     unbindRequest UnbindRequest 
                     searchRequest SearchRequest 
                    searchResEntry SearchResultEntry 
                     searchResDone SearchResultDone 
                      searchResRef SearchResultReference 
                     modifyRequest ModifyRequest 
                    modifyResponse ModifyResponse 
                        addRequest AddRequest 
                       addResponse AddResponse 
                        delRequest DelRequest 
                       delResponse DelResponse 
                      modDNRequest ModifyDNRequests 
                     modDNResponse ModifyDNResponse 
                    compareRequest CompareRequest 
                   compareResponse CompareResponse 
                    abandonRequest AbandonRequest 
                       extendedReq ExtendedRequest 
                      extendedResp ExtendedResponse 
     }

 **********************************************************************/

#define  LDAPPROTOCOL_MASK_BINDREQUEST                             0x00
#define  LDAPPROTOCOL_MASK_BINDRESPONSE                            0x01
#define  LDAPPROTOCOL_MASK_UNBINDREQUEST                           0x02
#define  LDAPPROTOCOL_MASK_SEARCHREQUEST                           0x03
#define  LDAPPROTOCOL_MASK_SEARCHRESENTRY                          0x04
#define  LDAPPROTOCOL_MASK_SEARCHRESDONE                           0x05
#define  LDAPPROTOCOL_MASK_SEARCHRESREF                            0x06
#define  LDAPPROTOCOL_MASK_MODIFYREQUEST                           0x07
#define  LDAPPROTOCOL_MASK_MODIFYRESPONSE                          0x08
#define  LDAPPROTOCOL_MASK_ADDREQUEST                              0x09
#define  LDAPPROTOCOL_MASK_ADDRESPONSE                             0x0A
#define  LDAPPROTOCOL_MASK_DELREQUEST                              0x0B
#define  LDAPPROTOCOL_MASK_DELRESPONSE                             0x0C
#define  LDAPPROTOCOL_MASK_MODDNREQUEST                            0x0D
#define  LDAPPROTOCOL_MASK_MODDNRESPONSE                           0x0E
#define  LDAPPROTOCOL_MASK_COMPAREREQUEST                          0x0F
#define  LDAPPROTOCOL_MASK_COMPARERESPONSE                         0x10
#define  LDAPPROTOCOL_MASK_ABANDONREQUEST                          0x11
#define  LDAPPROTOCOL_MASK_EXTENDEDREQ                             0x12
#define  LDAPPROTOCOL_MASK_EXTENDEDRESP                            0x13
#define  LDAPPROTOCOL_MAXI_MASK                                    0x13

#define  ANSC_ASN1_LDAPPROTOCOL_CLASS_CONTENT                         \
    /* duplication of the base object class content */                \
    ANSC_ASN1_CHOICE_CLASS_CONTENT                                    \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPPROTOCOL
{
    ANSC_ASN1_LDAPPROTOCOL_CLASS_CONTENT
}
ANSC_ASN1_LDAPPROTOCOL,  *PANSC_ASN1_LDAPPROTOCOL;

#define  ACCESS_ANSC_ASN1_LDAPPROTOCOL(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPPROTOCOL, Linkage)

/**********************************************************************

 OBJECT -- ASN1_CONTROLS

 Controls ::= SequenceOf Control  {}

 **********************************************************************/

#define  ANSC_ASN1_CONTROLS_CLASS_CONTENT                             \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_CONTROLS
{
    ANSC_ASN1_CONTROLS_CLASS_CONTENT
}
ANSC_ASN1_CONTROLS,  *PANSC_ASN1_CONTROLS;

#define  ACCESS_ANSC_ASN1_CONTROLS(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_CONTROLS, Linkage)

/**********************************************************************

 OBJECT -- ASN1_CONTROL

 Control ::= Sequence 
     {
                       controlType OctetString 
                       criticality BOOL DEF
                      controlValue OctetString OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_CONTROL_CLASS_CONTENT                              \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_CONTROL
{
    ANSC_ASN1_CONTROL_CLASS_CONTENT
}
ANSC_ASN1_CONTROL,  *PANSC_ASN1_CONTROL;

#define  ACCESS_ANSC_ASN1_CONTROL(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_CONTROL, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPSTRING

 LDAPString ::= OctetString 

 **********************************************************************/

#define  ANSC_ASN1_LDAPSTRING_CLASS_CONTENT                           \
    /* duplication of the base object class content */                \
    ANSC_ASN1_STRING_CLASS_CONTENT                                    \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPSTRING
{
    ANSC_ASN1_LDAPSTRING_CLASS_CONTENT
}
ANSC_ASN1_LDAPSTRING,  *PANSC_ASN1_LDAPSTRING;

#define  ACCESS_ANSC_ASN1_LDAPSTRING(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPSTRING, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MATCHINGRULEID

 MatchingRuleId ::= LDAPString 

 **********************************************************************/

#define  ANSC_ASN1_MATCHINGRULEID_CLASS_CONTENT                       \
    /* duplication of the base object class content */                \
    ANSC_ASN1_LDAPSTRING_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MATCHINGRULEID
{
    ANSC_ASN1_MATCHINGRULEID_CLASS_CONTENT
}
ANSC_ASN1_MATCHINGRULEID,  *PANSC_ASN1_MATCHINGRULEID;

#define  ACCESS_ANSC_ASN1_MATCHINGRULEID(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MATCHINGRULEID, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPATTRDESCLIST

 LDAPAttrDescList ::= SequenceOf OctetString  {}

 **********************************************************************/

#define  ANSC_ASN1_LDAPATTRDESCLIST_CLASS_CONTENT                     \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPATTRDESCLIST
{
    ANSC_ASN1_LDAPATTRDESCLIST_CLASS_CONTENT
}
ANSC_ASN1_LDAPATTRDESCLIST,  *PANSC_ASN1_LDAPATTRDESCLIST;

#define  ACCESS_ANSC_ASN1_LDAPATTRDESCLIST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPATTRDESCLIST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_ATTRVALUEASSERTION

 AttrValueAssertion ::= Sequence 
     {
                     attributeDesc OctetString 
                    assertionValue OctetString 
     }

 **********************************************************************/

#define  ANSC_ASN1_ATTRVALUEASSERTION_CLASS_CONTENT                   \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_ATTRVALUEASSERTION
{
    ANSC_ASN1_ATTRVALUEASSERTION_CLASS_CONTENT
}
ANSC_ASN1_ATTRVALUEASSERTION,  *PANSC_ASN1_ATTRVALUEASSERTION;

#define  ACCESS_ANSC_ASN1_ATTRVALUEASSERTION(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_ATTRVALUEASSERTION, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPATTRSET

 LDAPAttrSet ::= SetOf OctetString  {}

 **********************************************************************/

#define  ANSC_ASN1_LDAPATTRSET_CLASS_CONTENT                          \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SETOF_CLASS_CONTENT                                     \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPATTRSET
{
    ANSC_ASN1_LDAPATTRSET_CLASS_CONTENT
}
ANSC_ASN1_LDAPATTRSET,  *PANSC_ASN1_LDAPATTRSET;

#define  ACCESS_ANSC_ASN1_LDAPATTRSET(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPATTRSET, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPATTRIBUTE

 LDAPAttribute ::= Sequence 
     {
                          attrtype OctetString 
                              vals LDAPAttrSet 
     }

 **********************************************************************/

#define  ANSC_ASN1_LDAPATTRIBUTE_CLASS_CONTENT                        \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPATTRIBUTE
{
    ANSC_ASN1_LDAPATTRIBUTE_CLASS_CONTENT
}
ANSC_ASN1_LDAPATTRIBUTE,  *PANSC_ASN1_LDAPATTRIBUTE;

#define  ACCESS_ANSC_ASN1_LDAPATTRIBUTE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPATTRIBUTE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPRESULT

 LDAPResult ::= Sequence 
     {
                        resultCode Enumerate 
                         matchedDN OctetString 
                      errorMessage OctetString 
                          referral [CON 3] IMP Referral OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_LDAPRESULT_CLASS_CONTENT                           \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPRESULT
{
    ANSC_ASN1_LDAPRESULT_CLASS_CONTENT
}
ANSC_ASN1_LDAPRESULT,  *PANSC_ASN1_LDAPRESULT;

#define  ACCESS_ANSC_ASN1_LDAPRESULT(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPRESULT, Linkage)

/**********************************************************************

 OBJECT -- ASN1_REFERRAL

 Referral ::= SequenceOf OctetString  {}

 **********************************************************************/

#define  ANSC_ASN1_REFERRAL_CLASS_CONTENT                             \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_REFERRAL
{
    ANSC_ASN1_REFERRAL_CLASS_CONTENT
}
ANSC_ASN1_REFERRAL,  *PANSC_ASN1_REFERRAL;

#define  ACCESS_ANSC_ASN1_REFERRAL(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_REFERRAL, Linkage)

/**********************************************************************

 OBJECT -- ASN1_BINDREQUEST

 BindRequest ::=[APP 0] IMP Sequence 
     {
                           version Integer 
                           reqname OctetString 
                        authchoice AuthenticationChoice 
     }

 **********************************************************************/

#define  ANSC_ASN1_BINDREQUEST_CLASS_CONTENT                          \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_BINDREQUEST
{
    ANSC_ASN1_BINDREQUEST_CLASS_CONTENT
}
ANSC_ASN1_BINDREQUEST,  *PANSC_ASN1_BINDREQUEST;

#define  ACCESS_ANSC_ASN1_BINDREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_BINDREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_AUTHENTICATIONCHOICE

 AuthenticationChoice ::= Choice 
     {
                            simple [CON 0] IMP OctetString 
                              sasl [CON 3] IMP SaslCredentials 
     }

 **********************************************************************/

#define  AUTHENTICATIONCHOICE_MASK_SIMPLE                          0x00
#define  AUTHENTICATIONCHOICE_MASK_SASL                            0x01
#define  AUTHENTICATIONCHOICE_MAXI_MASK                            0x01

#define  ANSC_ASN1_AUTHENTICATIONCHOICE_CLASS_CONTENT                 \
    /* duplication of the base object class content */                \
    ANSC_ASN1_CHOICE_CLASS_CONTENT                                    \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_AUTHENTICATIONCHOICE
{
    ANSC_ASN1_AUTHENTICATIONCHOICE_CLASS_CONTENT
}
ANSC_ASN1_AUTHENTICATIONCHOICE,  *PANSC_ASN1_AUTHENTICATIONCHOICE;

#define  ACCESS_ANSC_ASN1_AUTHENTICATIONCHOICE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_AUTHENTICATIONCHOICE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SASLCREDENTIALS

 SaslCredentials ::= Sequence 
     {
                         mechanism OctetString 
                       credentials OctetString OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_SASLCREDENTIALS_CLASS_CONTENT                      \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SASLCREDENTIALS
{
    ANSC_ASN1_SASLCREDENTIALS_CLASS_CONTENT
}
ANSC_ASN1_SASLCREDENTIALS,  *PANSC_ASN1_SASLCREDENTIALS;

#define  ACCESS_ANSC_ASN1_SASLCREDENTIALS(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SASLCREDENTIALS, Linkage)

/**********************************************************************

 OBJECT -- ASN1_BINDRESPONSE

 BindResponse ::=[APP 1] IMP Sequence 
     {
                        resultCode Enumerate 
                         matchedDN LDAPString 
                      errorMessage LDAPString 
                          referral [CON 3] IMP Referral OPT
                   serverSaslCreds [CON 7] IMP OctetString OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_BINDRESPONSE_CLASS_CONTENT                         \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_BINDRESPONSE
{
    ANSC_ASN1_BINDRESPONSE_CLASS_CONTENT
}
ANSC_ASN1_BINDRESPONSE,  *PANSC_ASN1_BINDRESPONSE;

#define  ACCESS_ANSC_ASN1_BINDRESPONSE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_BINDRESPONSE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_UNBINDREQUEST

 UnbindRequest ::=[APP 2] IMP NULL 

 **********************************************************************/

#define  ANSC_ASN1_UNBINDREQUEST_CLASS_CONTENT                        \
    /* duplication of the base object class content */                \
    ANSC_ASN1_NULL_CLASS_CONTENT                                      \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_UNBINDREQUEST
{
    ANSC_ASN1_UNBINDREQUEST_CLASS_CONTENT
}
ANSC_ASN1_UNBINDREQUEST,  *PANSC_ASN1_UNBINDREQUEST;

#define  ACCESS_ANSC_ASN1_UNBINDREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_UNBINDREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SEARCHREQUEST

 SearchRequest ::=[APP 3] IMP Sequence 
     {
                        baseobject OctetString 
                             scope Enumerate 
                        derefAlias Enumerate 
                         sizeLimit Integer 
                         timeLimit Integer 
                         typesOnly BOOL 
                            filter Filter 
                        attributes LDAPAttrDescList 
     }

 **********************************************************************/

#define  ANSC_ASN1_SEARCHREQUEST_CLASS_CONTENT                        \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SEARCHREQUEST
{
    ANSC_ASN1_SEARCHREQUEST_CLASS_CONTENT
}
ANSC_ASN1_SEARCHREQUEST,  *PANSC_ASN1_SEARCHREQUEST;

#define  ACCESS_ANSC_ASN1_SEARCHREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SEARCHREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_FILTER

 Filter ::= Choice 
     {
                               and [CON 0] IMP Filters 
                                or [CON 1] IMP Filters 
                               not [CON 2] IMP Filter 
                     equalityMatch [CON 3] IMP AttrValueAssertion 
                        substrings [CON 4] IMP SubstringFilter 
                      greatOrEqual [CON 5] IMP AttrValueAssertion 
                       lessOrEqual [CON 6] IMP AttrValueAssertion 
                           present [CON 7] IMP OctetString 
                       approxMatch [CON 8] IMP AttrValueAssertion 
                   extensibleMatch [CON 9] IMP MatchingRuleAssersioin 
     }

 **********************************************************************/

#define  FILTER_MASK_AND                                           0x00
#define  FILTER_MASK_OR                                            0x01
#define  FILTER_MASK_NOT                                           0x02
#define  FILTER_MASK_EQUALITYMATCH                                 0x03
#define  FILTER_MASK_SUBSTRINGS                                    0x04
#define  FILTER_MASK_GREATOREQUAL                                  0x05
#define  FILTER_MASK_LESSOREQUAL                                   0x06
#define  FILTER_MASK_PRESENT                                       0x07
#define  FILTER_MASK_APPROXMATCH                                   0x08
#define  FILTER_MASK_EXTENSIBLEMATCH                               0x09
#define  FILTER_MAXI_MASK                                          0x09

#define  ANSC_ASN1_FILTER_CLASS_CONTENT                               \
    /* duplication of the base object class content */                \
    ANSC_ASN1_CHOICE_CLASS_CONTENT                                    \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_FILTER
{
    ANSC_ASN1_FILTER_CLASS_CONTENT
}
ANSC_ASN1_FILTER,  *PANSC_ASN1_FILTER;

#define  ACCESS_ANSC_ASN1_FILTER(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_FILTER, Linkage)

/**********************************************************************

 OBJECT -- ASN1_FILTERS

 Filters ::= SetOf Filter  {}

 **********************************************************************/

#define  ANSC_ASN1_FILTERS_CLASS_CONTENT                              \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SETOF_CLASS_CONTENT                                     \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_FILTERS
{
    ANSC_ASN1_FILTERS_CLASS_CONTENT
}
ANSC_ASN1_FILTERS,  *PANSC_ASN1_FILTERS;

#define  ACCESS_ANSC_ASN1_FILTERS(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_FILTERS, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SUBSTRINGFILTER

 SubstringFilter ::= Sequence 
     {
                        filterType OctetString 
                        substrings Substrings 
     }

 **********************************************************************/

#define  ANSC_ASN1_SUBSTRINGFILTER_CLASS_CONTENT                      \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SUBSTRINGFILTER
{
    ANSC_ASN1_SUBSTRINGFILTER_CLASS_CONTENT
}
ANSC_ASN1_SUBSTRINGFILTER,  *PANSC_ASN1_SUBSTRINGFILTER;

#define  ACCESS_ANSC_ASN1_SUBSTRINGFILTER(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SUBSTRINGFILTER, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MATCHINGRULEASSERSIOIN

 MatchingRuleAssersioin ::= Sequence 
     {
                      matchingRule [CON 1] IMP MatchingRuleId OPT
                         matchType [CON 2] IMP OctetString OPT
                        matchValue [CON 3] IMP OctetString 
                           dnAttrs [CON 4] IMP BOOL DEF
     }

 **********************************************************************/

#define  ANSC_ASN1_MATCHINGRULEASSERSIOIN_CLASS_CONTENT               \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MATCHINGRULEASSERSIOIN
{
    ANSC_ASN1_MATCHINGRULEASSERSIOIN_CLASS_CONTENT
}
ANSC_ASN1_MATCHINGRULEASSERSIOIN,  *PANSC_ASN1_MATCHINGRULEASSERSIOIN;

#define  ACCESS_ANSC_ASN1_MATCHINGRULEASSERSIOIN(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MATCHINGRULEASSERSIOIN, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SUBSTRINGS

 Substrings ::= SequenceOf SubstringChoice  {}

 **********************************************************************/

#define  ANSC_ASN1_SUBSTRINGS_CLASS_CONTENT                           \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SUBSTRINGS
{
    ANSC_ASN1_SUBSTRINGS_CLASS_CONTENT
}
ANSC_ASN1_SUBSTRINGS,  *PANSC_ASN1_SUBSTRINGS;

#define  ACCESS_ANSC_ASN1_SUBSTRINGS(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SUBSTRINGS, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SUBSTRINGCHOICE

 SubstringChoice ::= Choice 
     {
                          initials [CON 0] IMP LDAPString 
                               any [CON 1] IMP LDAPString 
                             final [CON 2] IMP LDAPString 
     }

 **********************************************************************/

#define  SUBSTRINGCHOICE_MASK_INITIALS                             0x00
#define  SUBSTRINGCHOICE_MASK_ANY                                  0x01
#define  SUBSTRINGCHOICE_MASK_FINAL                                0x02
#define  SUBSTRINGCHOICE_MAXI_MASK                                 0x02

#define  ANSC_ASN1_SUBSTRINGCHOICE_CLASS_CONTENT                      \
    /* duplication of the base object class content */                \
    ANSC_ASN1_CHOICE_CLASS_CONTENT                                    \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SUBSTRINGCHOICE
{
    ANSC_ASN1_SUBSTRINGCHOICE_CLASS_CONTENT
}
ANSC_ASN1_SUBSTRINGCHOICE,  *PANSC_ASN1_SUBSTRINGCHOICE;

#define  ACCESS_ANSC_ASN1_SUBSTRINGCHOICE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SUBSTRINGCHOICE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SEARCHRESULTENTRY

 SearchResultEntry ::=[APP 4] IMP Sequence 
     {
                        objectName OctetString 
                              attr PartialAttributeList 
     }

 **********************************************************************/

#define  ANSC_ASN1_SEARCHRESULTENTRY_CLASS_CONTENT                    \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SEARCHRESULTENTRY
{
    ANSC_ASN1_SEARCHRESULTENTRY_CLASS_CONTENT
}
ANSC_ASN1_SEARCHRESULTENTRY,  *PANSC_ASN1_SEARCHRESULTENTRY;

#define  ACCESS_ANSC_ASN1_SEARCHRESULTENTRY(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SEARCHRESULTENTRY, Linkage)

/**********************************************************************

 OBJECT -- ASN1_PARTIALATTRIBUTELIST

 PartialAttributeList ::= SequenceOf LDAPAttribute  {}

 **********************************************************************/

#define  ANSC_ASN1_PARTIALATTRIBUTELIST_CLASS_CONTENT                 \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_PARTIALATTRIBUTELIST
{
    ANSC_ASN1_PARTIALATTRIBUTELIST_CLASS_CONTENT
}
ANSC_ASN1_PARTIALATTRIBUTELIST,  *PANSC_ASN1_PARTIALATTRIBUTELIST;

#define  ACCESS_ANSC_ASN1_PARTIALATTRIBUTELIST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_PARTIALATTRIBUTELIST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SEARCHRESULTREFERENCE

 SearchResultReference ::=[APP 19] IMP SequenceOf OctetString  {}

 **********************************************************************/

#define  ANSC_ASN1_SEARCHRESULTREFERENCE_CLASS_CONTENT                \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SEARCHRESULTREFERENCE
{
    ANSC_ASN1_SEARCHRESULTREFERENCE_CLASS_CONTENT
}
ANSC_ASN1_SEARCHRESULTREFERENCE,  *PANSC_ASN1_SEARCHRESULTREFERENCE;

#define  ACCESS_ANSC_ASN1_SEARCHRESULTREFERENCE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SEARCHRESULTREFERENCE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_SEARCHRESULTDONE

 SearchResultDone ::=[APP 5] IMP LDAPResult 

 **********************************************************************/

#define  ANSC_ASN1_SEARCHRESULTDONE_CLASS_CONTENT                     \
    /* duplication of the base object class content */                \
    ANSC_ASN1_LDAPRESULT_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_SEARCHRESULTDONE
{
    ANSC_ASN1_SEARCHRESULTDONE_CLASS_CONTENT
}
ANSC_ASN1_SEARCHRESULTDONE,  *PANSC_ASN1_SEARCHRESULTDONE;

#define  ACCESS_ANSC_ASN1_SEARCHRESULTDONE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_SEARCHRESULTDONE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MODIFYREQUEST

 ModifyRequest ::=[APP 6] IMP Sequence 
     {
                            object OctetString 
                     modifications Modifications 
     }

 **********************************************************************/

#define  ANSC_ASN1_MODIFYREQUEST_CLASS_CONTENT                        \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MODIFYREQUEST
{
    ANSC_ASN1_MODIFYREQUEST_CLASS_CONTENT
}
ANSC_ASN1_MODIFYREQUEST,  *PANSC_ASN1_MODIFYREQUEST;

#define  ACCESS_ANSC_ASN1_MODIFYREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MODIFYREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MODIFYRESPONSE

 ModifyResponse ::=[APP 7] IMP LDAPResult 

 **********************************************************************/

#define  ANSC_ASN1_MODIFYRESPONSE_CLASS_CONTENT                       \
    /* duplication of the base object class content */                \
    ANSC_ASN1_LDAPRESULT_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MODIFYRESPONSE
{
    ANSC_ASN1_MODIFYRESPONSE_CLASS_CONTENT
}
ANSC_ASN1_MODIFYRESPONSE,  *PANSC_ASN1_MODIFYRESPONSE;

#define  ACCESS_ANSC_ASN1_MODIFYRESPONSE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MODIFYRESPONSE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_ADDREQUEST

 AddRequest ::=[APP 8] IMP Sequence 
     {
                             entry OctetString 
                          attrlist LDAPAttrList 
     }

 **********************************************************************/

#define  ANSC_ASN1_ADDREQUEST_CLASS_CONTENT                           \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_ADDREQUEST
{
    ANSC_ASN1_ADDREQUEST_CLASS_CONTENT
}
ANSC_ASN1_ADDREQUEST,  *PANSC_ASN1_ADDREQUEST;

#define  ACCESS_ANSC_ASN1_ADDREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_ADDREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPATTRLIST

 LDAPAttrList ::= SequenceOf LDAPAttribute  {}

 **********************************************************************/

#define  ANSC_ASN1_LDAPATTRLIST_CLASS_CONTENT                         \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPATTRLIST
{
    ANSC_ASN1_LDAPATTRLIST_CLASS_CONTENT
}
ANSC_ASN1_LDAPATTRLIST,  *PANSC_ASN1_LDAPATTRLIST;

#define  ACCESS_ANSC_ASN1_LDAPATTRLIST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPATTRLIST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_LDAPATTRTYPEANDVALUES

 LDAPAttrTypeAndValues ::= Sequence 
     {
                          attrType OctetString 
                              vals LDAPAttrSet 
     }

 **********************************************************************/

#define  ANSC_ASN1_LDAPATTRTYPEANDVALUES_CLASS_CONTENT                \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_LDAPATTRTYPEANDVALUES
{
    ANSC_ASN1_LDAPATTRTYPEANDVALUES_CLASS_CONTENT
}
ANSC_ASN1_LDAPATTRTYPEANDVALUES,  *PANSC_ASN1_LDAPATTRTYPEANDVALUES;

#define  ACCESS_ANSC_ASN1_LDAPATTRTYPEANDVALUES(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_LDAPATTRTYPEANDVALUES, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MODIFICATION

 Modification ::= Sequence 
     {
                         operation Enumerate 
                     typeAndValues LDAPAttrTypeAndValues 
     }

 **********************************************************************/

#define  ANSC_ASN1_MODIFICATION_CLASS_CONTENT                         \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MODIFICATION
{
    ANSC_ASN1_MODIFICATION_CLASS_CONTENT
}
ANSC_ASN1_MODIFICATION,  *PANSC_ASN1_MODIFICATION;

#define  ACCESS_ANSC_ASN1_MODIFICATION(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MODIFICATION, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MODIFICATIONS

 Modifications ::= SequenceOf Modification  {}

 **********************************************************************/

#define  ANSC_ASN1_MODIFICATIONS_CLASS_CONTENT                        \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCEOF_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MODIFICATIONS
{
    ANSC_ASN1_MODIFICATIONS_CLASS_CONTENT
}
ANSC_ASN1_MODIFICATIONS,  *PANSC_ASN1_MODIFICATIONS;

#define  ACCESS_ANSC_ASN1_MODIFICATIONS(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MODIFICATIONS, Linkage)

/**********************************************************************

 OBJECT -- ASN1_ADDRESPONSE

 AddResponse ::=[APP 9] IMP LDAPResult 

 **********************************************************************/

#define  ANSC_ASN1_ADDRESPONSE_CLASS_CONTENT                          \
    /* duplication of the base object class content */                \
    ANSC_ASN1_LDAPRESULT_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_ADDRESPONSE
{
    ANSC_ASN1_ADDRESPONSE_CLASS_CONTENT
}
ANSC_ASN1_ADDRESPONSE,  *PANSC_ASN1_ADDRESPONSE;

#define  ACCESS_ANSC_ASN1_ADDRESPONSE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_ADDRESPONSE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_DELREQUEST

 DelRequest ::=[APP 10] IMP OctetString 

 **********************************************************************/

#define  ANSC_ASN1_DELREQUEST_CLASS_CONTENT                           \
    /* duplication of the base object class content */                \
    ANSC_ASN1_STRING_CLASS_CONTENT                                    \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_DELREQUEST
{
    ANSC_ASN1_DELREQUEST_CLASS_CONTENT
}
ANSC_ASN1_DELREQUEST,  *PANSC_ASN1_DELREQUEST;

#define  ACCESS_ANSC_ASN1_DELREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_DELREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_DELRESPONSE

 DelResponse ::=[APP 11] IMP LDAPResult 

 **********************************************************************/

#define  ANSC_ASN1_DELRESPONSE_CLASS_CONTENT                          \
    /* duplication of the base object class content */                \
    ANSC_ASN1_LDAPRESULT_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_DELRESPONSE
{
    ANSC_ASN1_DELRESPONSE_CLASS_CONTENT
}
ANSC_ASN1_DELRESPONSE,  *PANSC_ASN1_DELRESPONSE;

#define  ACCESS_ANSC_ASN1_DELRESPONSE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_DELRESPONSE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MODIFYDNREQUESTS

 ModifyDNRequests ::=[APP 12] IMP Sequence 
     {
                             entry OctetString 
                            newrdn OctetString 
                       deleteOldDn BOOL 
                       newSuperior [CON 0] IMP OctetString OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_MODIFYDNREQUESTS_CLASS_CONTENT                     \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MODIFYDNREQUESTS
{
    ANSC_ASN1_MODIFYDNREQUESTS_CLASS_CONTENT
}
ANSC_ASN1_MODIFYDNREQUESTS,  *PANSC_ASN1_MODIFYDNREQUESTS;

#define  ACCESS_ANSC_ASN1_MODIFYDNREQUESTS(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MODIFYDNREQUESTS, Linkage)

/**********************************************************************

 OBJECT -- ASN1_MODIFYDNRESPONSE

 ModifyDNResponse ::=[APP 13] IMP LDAPResult 

 **********************************************************************/

#define  ANSC_ASN1_MODIFYDNRESPONSE_CLASS_CONTENT                     \
    /* duplication of the base object class content */                \
    ANSC_ASN1_LDAPRESULT_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_MODIFYDNRESPONSE
{
    ANSC_ASN1_MODIFYDNRESPONSE_CLASS_CONTENT
}
ANSC_ASN1_MODIFYDNRESPONSE,  *PANSC_ASN1_MODIFYDNRESPONSE;

#define  ACCESS_ANSC_ASN1_MODIFYDNRESPONSE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_MODIFYDNRESPONSE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_COMPAREREQUEST

 CompareRequest ::=[APP 14] IMP Sequence 
     {
                             entry OctetString 
                               ava AttrValueAssertion 
     }

 **********************************************************************/

#define  ANSC_ASN1_COMPAREREQUEST_CLASS_CONTENT                       \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_COMPAREREQUEST
{
    ANSC_ASN1_COMPAREREQUEST_CLASS_CONTENT
}
ANSC_ASN1_COMPAREREQUEST,  *PANSC_ASN1_COMPAREREQUEST;

#define  ACCESS_ANSC_ASN1_COMPAREREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_COMPAREREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_COMPARERESPONSE

 CompareResponse ::=[APP 15] IMP LDAPResult 

 **********************************************************************/

#define  ANSC_ASN1_COMPARERESPONSE_CLASS_CONTENT                      \
    /* duplication of the base object class content */                \
    ANSC_ASN1_LDAPRESULT_CLASS_CONTENT                                \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_COMPARERESPONSE
{
    ANSC_ASN1_COMPARERESPONSE_CLASS_CONTENT
}
ANSC_ASN1_COMPARERESPONSE,  *PANSC_ASN1_COMPARERESPONSE;

#define  ACCESS_ANSC_ASN1_COMPARERESPONSE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_COMPARERESPONSE, Linkage)

/**********************************************************************

 OBJECT -- ASN1_ABANDONREQUEST

 AbandonRequest ::=[APP 16] IMP Integer 

 **********************************************************************/

#define  ANSC_ASN1_ABANDONREQUEST_CLASS_CONTENT                       \
    /* duplication of the base object class content */                \
    ANSC_ASN1_INTEGER_CLASS_CONTENT                                   \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_ABANDONREQUEST
{
    ANSC_ASN1_ABANDONREQUEST_CLASS_CONTENT
}
ANSC_ASN1_ABANDONREQUEST,  *PANSC_ASN1_ABANDONREQUEST;

#define  ACCESS_ANSC_ASN1_ABANDONREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_ABANDONREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_EXTENDEDREQUEST

 ExtendedRequest ::=[APP 23] IMP Sequence 
     {
                       requestName [CON 0] IMP OctetString 
                      requestValue [CON 1] IMP OctetString OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_EXTENDEDREQUEST_CLASS_CONTENT                      \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_EXTENDEDREQUEST
{
    ANSC_ASN1_EXTENDEDREQUEST_CLASS_CONTENT
}
ANSC_ASN1_EXTENDEDREQUEST,  *PANSC_ASN1_EXTENDEDREQUEST;

#define  ACCESS_ANSC_ASN1_EXTENDEDREQUEST(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_EXTENDEDREQUEST, Linkage)

/**********************************************************************

 OBJECT -- ASN1_EXTENDEDRESPONSE

 ExtendedResponse ::=[APP 24] IMP Sequence 
     {
                        resultCode Enumerate 
                         matchedDN LDAPString 
                      errorMessage LDAPString 
                          referral [CON 3] IMP Referral OPT
                      responsename [CON 10] IMP OctetString OPT
                          response [CON 11] IMP OctetString OPT
     }

 **********************************************************************/

#define  ANSC_ASN1_EXTENDEDRESPONSE_CLASS_CONTENT                     \
    /* duplication of the base object class content */                \
    ANSC_ASN1_SEQUENCE_CLASS_CONTENT                                  \
    /* start of object class content */                               \
    /* end of object class content */                                 \

typedef  struct
_ANSC_ASN1_EXTENDEDRESPONSE
{
    ANSC_ASN1_EXTENDEDRESPONSE_CLASS_CONTENT
}
ANSC_ASN1_EXTENDEDRESPONSE,  *PANSC_ASN1_EXTENDEDRESPONSE;

#define  ACCESS_ANSC_ASN1_EXTENDEDRESPONSE(p)    \
         ACCESS_CONTAINER(p, ANSC_ASN1_EXTENDEDRESPONSE, Linkage)


#endif  /* _ASN1_LDAPMESSAGE_INTERFACE_H */

