/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: smartcard_sample_interface.h

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        This interface is for the entity of PKI implementation.

        The entity is responsible for generating key pair, pkcs10
        certificate request, self-signed certificate.

    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        Bin Zhu

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   08/19/2002  initial revision

 **********************************************************************/


#ifndef  _SMARTCARD_SAMPLE_INTERFACE_H
#define  _SMARTCARD_SAMPLE_INTERFACE_H

typedef ANSC_STATUS
(*SC_REMOVE)
    (
        ANSC_HANDLE                 hThisObject
    );

#define  SMARTCARD_ENTITY_CLASS_CONTENT                               \
    /* start of object class content */                               \
    ANSC_CRYPT_API_CLASS_CONTENT                                      \
    SC_REMOVE                       Remove;                           \
    ANSC_HANDLE                     hCryptoSSL;                       \
    ANSC_HANDLE                     hKeyPairHandle;                   \
    PKI_KEY_TYPE                    KeyType;                          \
    ULONG                           KeyLength;                        \
    /* end of object class content */                                 \


typedef  struct
_SAMPLE_SMARTCARD_ENTITY
{
    SMARTCARD_ENTITY_CLASS_CONTENT
}
SAMPLE_SMARTCARD_ENTITY,  *PSAMPLE_SMARTCARD_ENTITY;


/***********************************************************************
 *
 *  Exported API
 *
 ***********************************************************************/
ANSC_HANDLE
AnscPKICreateSampleSmartCardEntity
    (
        PKI_KEY_TYPE               type,
        ULONG                      length  /* in Bytes */
    );

#endif  /*_SMARTCARD_SAMPLE_INTERFACE_H*/


