/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/**********************************************************************

    MODULE: ansc_asn1_PublicKey.c

        ASN.1 ANSC Code Generated by Cisco Systems, Inc.

    ---------------------------------------------------------------

    DESCRIPTION:

        The ASN.1 objects implemented in this file

        *   ANSC_ASN1_PUBLICKEY
        *   ANSC_ASN1_RSAPUBLICKEY
        *   ANSC_ASN1_DSAPUBLICKEY
        *   ANSC_ASN1_DHPUBLICKEY
        *   ANSC_ASN1_KEYPAIR

    ---------------------------------------------------------------

    ENVIRONMENT:

        platform independent

    ---------------------------------------------------------------

    AUTHOR:

        ASNMAGIC ANSC CODE GENERATOR 1.0

    ---------------------------------------------------------------

    REVISION HISTORY:

        *   05/07/2002  initial revision
        *   08/09/2002  encryption functions are added
        *   08/13/2002  dhpublickey is added;
        *   08/14/2002  function added to check key matched or not

 **********************************************************************/

#include "ansc_asn1_advanced_local.h"

static
BOOLEAN
isIntegerMatching
    (
        PUCHAR                      pValue1,
        ULONG                       uLength1,
        PUCHAR                      pValue2,
        ULONG                       uLength2
    )
{
    ULONG                           uSign1   = 0;
    ULONG                           uSign2   = 0;

    if( pValue1[0] == 0x00) 
    {
        uSign1 = 1;
    }

    if( pValue2[0] == 0x00)
    {
        uSign2 = 1;
    }

    if( uLength1 - uSign1 != uLength2 - uSign2)
    {
        return FALSE;
    }

    return 
        AnscEqualMemory
            (
                (PVOID)(pValue1 + uSign1),
                (PVOID)(pValue2 + uSign2),
                uLength1 - uSign1
            );
}

/**********************************************************************

 OBJECT -- ANSC_ASN1_PUBLICKEY

 PublicKey ::= Choice 
     {
                      dsaPublicKey DSAPublicKey 
                      rsaPublicKey RSAPublicKey 
                      dhPublicKey  DHPublicKey
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreatePublicKey
    (
        ANSC_HANDLE                 hReserved
    )
{
    PANSC_ASN1_PUBLICKEY            pThisObject  = NULL;

    /*
     * Create the base ASN.1 object.
     */
    if( hReserved != NULL)
    {
        pThisObject = (PANSC_ASN1_PUBLICKEY)
            AnscAsn1CreateChoice
                (
                    hReserved
                );
    }
    else
    {
        pThisObject = (PANSC_ASN1_PUBLICKEY)
            AnscAsn1CreateChoice
                (
                    (ANSC_HANDLE)sizeof(ANSC_ASN1_PUBLICKEY)
                );
    }

    if( pThisObject == NULL)
    {
        return (ANSC_HANDLE)NULL;
    }

    /*
     * Initialize the common variables and functions for this ASN.1 object.
     */
    pThisObject->SetClassName(pThisObject, "ANSC_ASN1_PUBLICKEY");
    pThisObject->SetName(pThisObject, "PublicKey");

    pThisObject->Create             = AnscAsn1CreatePublicKey;
    pThisObject->CreateSelection    = AnscAsn1PublicKeyCreateSelection;
    pThisObject->GetSelectionName   = AnscAsn1PublicKeyGetSelectionName;
    pThisObject->GetChoiceFromOID   = AnscAsn1PublicKeyGetChoiceByOID;
    pThisObject->GetOIDValueByMask  = AnscAsn1PublicKeyGetOIDValueByMask;
    pThisObject->Verify             = AnscAsn1PublicKeyVerify;
    pThisObject->Encrypt            = AnscAsn1PublicKeyEncrypt;
    pThisObject->IsKeyMatching      = AnscAsn1PublicKeyIsKeyMatching;
    pThisObject->ExportPublicKey    = AnscAsn1PublicKeyExportPublicKey;

    pThisObject->uTotalChoice       = PUBLICKEY_MAXI_MASK + 1;
    pThisObject->bChoiceByOID       = TRUE;

    return (ANSC_HANDLE)pThisObject;
}

ANSC_HANDLE
AnscAsn1PublicKeyCreateSelection
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       index
    )
{
    PANSC_ASN1_OBJECT               pThisObject      = NULL;
    PANSC_ASN1_CHOICE               pParent         = (PANSC_ASN1_CHOICE)hThisObject;

    switch( index )
    {

        case PUBLICKEY_MASK_DSAPUBLICKEY:

            pThisObject = AnscAsn1CreateDSAPublicKey(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateSelectionAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetSelectionName(pParent,index));
            }

            break;

        case PUBLICKEY_MASK_RSAPUBLICKEY:

            pThisObject = AnscAsn1CreateRSAPublicKey(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateSelectionAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetSelectionName(pParent,index));
            }

            break;

        case PUBLICKEY_MASK_DHPUBLICKEY:

            pThisObject = AnscAsn1CreateDHPublicKey(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateSelectionAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetSelectionName(pParent,index));
            }

            break;

    }

    return pThisObject;

}

PCHAR
AnscAsn1PublicKeyGetSelectionName
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       selType
    )
{
    UNREFERENCED_PARAMETER(hThisObject);
    switch ( selType )
    {
        case PUBLICKEY_MASK_DSAPUBLICKEY:

            return"dsaPublicKey";

        case PUBLICKEY_MASK_RSAPUBLICKEY:

            return"rsaPublicKey";

        case PUBLICKEY_MASK_DHPUBLICKEY:

            return"dhPublicKey";
    }

    return "";

}

LONG
AnscAsn1PublicKeyGetChoiceByOID
    (
        ANSC_HANDLE                 hThisObject,
        PCHAR                       pOIDString
    )
{
    UNREFERENCED_PARAMETER(hThisObject);
    if( pOIDString == NULL)         return -1;

    if( AnscEqualString1(pOIDString,"1.2.840.10040.4.1",FALSE))
    {
        return PUBLICKEY_MASK_DSAPUBLICKEY;
    }
    else if( AnscEqualString1(pOIDString,"1.2.840.113549.1.1.1",FALSE))
    {
        return PUBLICKEY_MASK_RSAPUBLICKEY;
    }
    else if( AnscEqualString1(pOIDString,"1.2.840.113549.1.1.5",FALSE))
    {
        return PUBLICKEY_MASK_RSAPUBLICKEY;
    }
    else if( AnscEqualString1(pOIDString,"1.2.840.113549.1.1.2",FALSE))
    {
        return PUBLICKEY_MASK_RSAPUBLICKEY;
    }
    else if( AnscEqualString1(pOIDString,"1.2.840.113549.1.1.4",FALSE))
    {
        return PUBLICKEY_MASK_RSAPUBLICKEY;
    }
    else if( AnscEqualString1(pOIDString,"1.3.14.3.2.29",FALSE))
    {
        return PUBLICKEY_MASK_RSAPUBLICKEY;
    }
    else if( AnscEqualString1(pOIDString,"1.2.840.10040.4.3",FALSE))
    {
        return PUBLICKEY_MASK_DSAPUBLICKEY;
    }
    else if( AnscEqualString1(pOIDString,"1.2.840.10046.2.1",FALSE))
    {
        return PUBLICKEY_MASK_DHPUBLICKEY;
    }

    return -1;

}

PCHAR
AnscAsn1PublicKeyGetOIDValueByMask
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       selType
    )
{
    UNREFERENCED_PARAMETER(hThisObject);
    switch ( selType )
    {
        case PUBLICKEY_MASK_DSAPUBLICKEY:

             return "1.2.840.10040.4.1";

        case PUBLICKEY_MASK_RSAPUBLICKEY:

             return "1.2.840.113549.1.1.1";

        case PUBLICKEY_MASK_DHPUBLICKEY:

             return "1.2.840.10046.2.1";

        /*
        case PUBLICKEY_MASK_RSAPUBLICKEY:

             return "1.2.840.113549.1.1.5";
        */

        /*
        case PUBLICKEY_MASK_RSAPUBLICKEY:

             return "1.2.840.113549.1.1.2";
        */

        /*
        case PUBLICKEY_MASK_RSAPUBLICKEY:

             return "1.2.840.113549.1.1.4";
        */

        /*
        case PUBLICKEY_MASK_RSAPUBLICKEY:

             return "1.3.14.3.2.29";
        */

        /*
        case PUBLICKEY_MASK_DSAPUBLICKEY:

             return "1.2.840.10040.4.3";
        */

    }

    return NULL;

}

/*
 *  Manually added functions;
 */
ANSC_STATUS
AnscAsn1PublicKeyVerify
    (
        ANSC_HANDLE                 hThisHandle,
        ANSC_HANDLE                 hParams,
        PUCHAR                      pDataSigned,
        ULONG                       lengthOfData,
        SIGNATURE_TYPE              signType,
        PUCHAR                      pSignature,
        ULONG                       uLength
    )
{
    PANSC_ASN1_PUBLICKEY            pPublicKey   = (PANSC_ASN1_PUBLICKEY)hThisHandle;
    PANSC_ASN1_OBJECT               pKeyObject;

    if( hThisHandle == NULL)
    {
        return ANSC_ASN1_BAD_PARAMETER;
    }
    

    pKeyObject = (PANSC_ASN1_OBJECT)pPublicKey->hSelection;

    if( pKeyObject == NULL)
    {
        return ANSC_ASN1_NULL_OBJCET;
    }

    if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_RSAPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_RSAPUBLICKEY)pKeyObject)->Verify
                    (
                        pKeyObject,
                        hParams,
                        pDataSigned,
                        lengthOfData,
                        signType,
                        pSignature,
                        uLength
                    );

    }
    else if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_DSAPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_DSAPUBLICKEY)pKeyObject)->Verify
                    (
                        pKeyObject,
                        hParams,
                        pDataSigned,
                        lengthOfData,
                        signType,
                        pSignature,
                        uLength
                    );
    }

    return ANSC_ASN1_NOT_SUPPORTED;
}

ANSC_STATUS
AnscAsn1PublicKeyEncrypt
    (
        ANSC_HANDLE                 hThisHandle,           
        PUCHAR                      pDataWillBeEncrypted,
        ULONG                       lengthOfData,
        PUCHAR                      pDataEncrypted,
        PULONG                      pLength
    )
{
    PANSC_ASN1_PUBLICKEY            pPublicKey   = (PANSC_ASN1_PUBLICKEY)hThisHandle;
    PANSC_ASN1_OBJECT               pKeyObject;

    if( hThisHandle == NULL)
    {
        return ANSC_ASN1_BAD_PARAMETER;
    }
    

    pKeyObject = (PANSC_ASN1_OBJECT)pPublicKey->hSelection;

    if( pKeyObject == NULL)
    {
        return ANSC_ASN1_NULL_OBJCET;
    }

    if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_RSAPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_RSAPUBLICKEY)pKeyObject)->Encrypt
                    (
                        pKeyObject,
                        pDataWillBeEncrypted,
                        lengthOfData,
                        pDataEncrypted,
                        pLength
                    );

    }

    return ANSC_ASN1_NOT_SUPPORTED;

}

BOOLEAN
AnscAsn1PublicKeyIsKeyMatching
    (
        ANSC_HANDLE                 hThisHandle,
        PKI_KEY_TYPE                keyType,
        ANSC_HANDLE                 hKeyParams
    )
{
    PANSC_ASN1_PUBLICKEY            pPublicKey   = (PANSC_ASN1_PUBLICKEY)hThisHandle;
    PANSC_ASN1_OBJECT               pKeyObject;

    if( hThisHandle == NULL)
    {
        return FALSE;
    }
    

    pKeyObject = (PANSC_ASN1_OBJECT)pPublicKey->hSelection;

    if( pKeyObject == NULL)
    {
        return FALSE;
    }

    if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_RSAPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_RSAPUBLICKEY)pKeyObject)->IsKeyMatching
                    (
                        pKeyObject,
                        keyType,
                        hKeyParams
                    );

    }
    else if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_DSAPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_DSAPUBLICKEY)pKeyObject)->IsKeyMatching
                    (
                        pKeyObject,
                        keyType,
                        hKeyParams
                    );
    }
    else if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_DHPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_DHPUBLICKEY)pKeyObject)->IsKeyMatching
                    (
                        pKeyObject,
                        keyType,
                        hKeyParams
                    );
    }

    return FALSE;
}

ANSC_STATUS
AnscAsn1PublicKeyExportPublicKey
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hKeyGenParams
    )
{
    PANSC_ASN1_PUBLICKEY            pPublicKey   = (PANSC_ASN1_PUBLICKEY)hThisObject;
    PANSC_ASN1_OBJECT               pKeyObject;

    if( hThisObject == NULL)
    {
        return FALSE;
    }
    

    pKeyObject = (PANSC_ASN1_OBJECT)pPublicKey->hSelection;

    if( pKeyObject == NULL)
    {
        return FALSE;
    }

    if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_RSAPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_RSAPUBLICKEY)pKeyObject)->ExportPublicKey
                    (
                        pKeyObject,
                        hKeyGenParams
                    );

    }
    else if( AnscEqualString1(pKeyObject->ClassName,"ANSC_ASN1_DSAPUBLICKEY",FALSE))
    {
        return ((PANSC_ASN1_DSAPUBLICKEY)pKeyObject)->ExportPublicKey
                    (
                        pKeyObject,
                        hKeyGenParams
                    );
    }

    return ANSC_STATUS_FAILURE;
}

/**********************************************************************

 OBJECT -- ANSC_ASN1_RSAPUBLICKEY

 RSAPublicKey ::= Sequence 
     {
                           modulus Integer 
                    publicExponent Integer 
     }

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateRSAPublicKey
    (
        ANSC_HANDLE                 hReserved
    )
{
    PANSC_ASN1_RSAPUBLICKEY         pThisObject  = NULL;

    /*
     * Create the base ASN.1 object.
     */
    if( hReserved != NULL)
    {
        pThisObject = (PANSC_ASN1_RSAPUBLICKEY)
            AnscAsn1CreateSequence
                (
                    hReserved
                );
    }
    else
    {
        pThisObject = (PANSC_ASN1_RSAPUBLICKEY)
            AnscAsn1CreateSequence
                (
                    (ANSC_HANDLE)sizeof(ANSC_ASN1_RSAPUBLICKEY)
                );
    }

    if( pThisObject == NULL)
    {
        return (ANSC_HANDLE)NULL;
    }

    /*
     * Initialize the common variables and functions for this ASN.1 object.
     */
    pThisObject->SetClassName(pThisObject, "ANSC_ASN1_RSAPUBLICKEY");
    pThisObject->SetName(pThisObject, "RSAPublicKey");

    pThisObject->Create             = AnscAsn1CreateRSAPublicKey;
    pThisObject->CreateChildAttr    = AnscAsn1RSAPublicKeyCreateChildAttr;
    pThisObject->GetChildName       = AnscAsn1RSAPublicKeyGetChildName;
    pThisObject->CreateChildObject  = AnscAsn1RSAPublicKeyCreateChildObject;
    pThisObject->Verify             = AnscAsn1RSAPublicKeyVerify;
    pThisObject->Encrypt            = AnscAsn1RSAPublicKeyEncrypt;
    pThisObject->InitKey            = AnscAsn1RSAPublicKeyInitKey;
    pThisObject->IsKeyMatching      = AnscAsn1RSAPublicKeyIsKeyMatching;
    pThisObject->ExportPublicKey    = AnscAsn1RSAPublicKeyExportPublicKey;

    pThisObject->uTotalChild        = 2;

    /*
     * Create all the children
     */
    pThisObject->CreateAllChildren(pThisObject);


    return (ANSC_HANDLE)pThisObject;
}

ANSC_HANDLE
AnscAsn1RSAPublicKeyCreateChildObject
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       index
    )
{
    PANSC_ASN1_OBJECT               pThisObject      = NULL;
    PANSC_ASN1_SEQUENCE             pParent          = (PANSC_ASN1_SEQUENCE)hThisObject;

    switch( index )
    {

        case 0:

            pThisObject = AnscAsn1CreateInteger(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateChildAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetChildName(pParent,index));
            }

            break;

        case 1:

            pThisObject = AnscAsn1CreateInteger(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateChildAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetChildName(pParent,index));
            }

            break;

    }

    return pThisObject;

}

PANSC_ATTR_OBJECT
AnscAsn1RSAPublicKeyCreateChildAttr
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       index
    )
{
    UNREFERENCED_PARAMETER(hThisObject);
    UNREFERENCED_PARAMETER(index);
    PANSC_ATTR_OBJECT               pAttrObject  = NULL;

    return pAttrObject;

}

PCHAR
AnscAsn1RSAPublicKeyGetChildName
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       index
    )
{
#ifndef _PKI_KERNEL
    UNREFERENCED_PARAMETER(hThisObject);
    switch ( index )
    {
        case 0:

            return"modulus";

        case 1:

            return"publicExponent";

    }

#endif

    return "";

}


/*
 *  Manually added functions;
 */
ANSC_STATUS
AnscAsn1RSAPublicKeyVerify
    (
        ANSC_HANDLE                 hThisHandle,
        ANSC_HANDLE                 hParams,
        PUCHAR                      pDataSigned,
        ULONG                       lengthOfData,
        SIGNATURE_TYPE              SignatureType,
        PUCHAR                      pSignature,
        ULONG                       uLength
    )
{
    UNREFERENCED_PARAMETER(hParams);
    /* for RSA, hParams is NULL, don't need to care about it */
    PANSC_ASN1_RSAPUBLICKEY         pRSA        = (PANSC_ASN1_RSAPUBLICKEY)hThisHandle;
    ANSC_STATUS                     status;
    PANSC_CRYPTO_RSA_PUBLIC_KEY     pPublic;
    PANSC_CRYPTO_PUB_SSLEAY_OBJECT  pCrypto;
    PANSC_ASN1_INTEGER              pInteger;
    PANSC_CRYPTO_PUB_KEY_PARAMS     pParams;
    int                             nHashMethod;

    if( pRSA == NULL)
    {
        return ANSC_ASN1_BAD_PARAMETER;
    }

    if( uLength == 0 || pSignature == NULL || pDataSigned == NULL)
    {
        return ANSC_ASN1_INVALID_SIGNATURE;
    }

    if( SignatureType != RSA_SHA1_SIGNATURE && SignatureType != RSA_MD5_SIGNATURE
        && SignatureType != RSA_MD2_SIGNATURE && SignatureType != RSA_MD4_SIGNATURE)
    {
        return ANSC_ASN1_NOT_SUPPORTED;
    }

    if( SignatureType == RSA_SHA1_SIGNATURE)
    {
        nHashMethod = RSA_VERIFY_WITH_SHA1;
    }
    else if( SignatureType == RSA_MD2_SIGNATURE)
    {
        nHashMethod = RSA_VERIFY_WITH_MD2;
    }
    else if( SignatureType == RSA_MD4_SIGNATURE)
    {
        nHashMethod = RSA_VERIFY_WITH_MD4;
    }
    else
    {
        nHashMethod = RSA_VERIFY_WITH_MD5;
    }


    pCrypto     = (PANSC_CRYPTO_PUB_SSLEAY_OBJECT)AnscCreateCryptoPubSSLeay(NULL);

    if (pCrypto == NULL)
    {
        return ANSC_ASN1_NO_RESOURCES;
    }

    pParams = (PANSC_CRYPTO_PUB_KEY_PARAMS)AnscAllocateMemory(sizeof(ANSC_CRYPTO_PUB_KEY_PARAMS));

    if( pParams == NULL)
    {
        pCrypto->Remove(pCrypto); 

        return ANSC_ASN1_NO_RESOURCES;
    }

    pPublic    = (PANSC_CRYPTO_RSA_PUBLIC_KEY)&pParams->Key.RSA.RsaPublicKey;

    /* RSA public key */
    pInteger    = (PANSC_ASN1_INTEGER)pRSA->GetChildByIndex(pRSA,0);
    pPublic->Modulus.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->Modulus.Data, pInteger->pValueBuffer, pPublic->Modulus.Length);

    pInteger    = (PANSC_ASN1_INTEGER)pRSA->GetChildByIndex(pRSA,1);
    pPublic->PublicExponent.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->PublicExponent.Data.ucData, pInteger->pValueBuffer,pPublic->PublicExponent.Length);

    /* verify */
    status = 
        pCrypto->RSAHashAndVerify
                (
                    nHashMethod,
                    (PVOID)pDataSigned,
                    lengthOfData,
                    pSignature,
                    uLength,
                    pParams
                );
 
    pCrypto->Remove(pCrypto); 
    AnscFreeMemory(pParams);

    return status;
}

ANSC_STATUS
AnscAsn1RSAPublicKeyEncrypt
    (
        ANSC_HANDLE                 hThisObject,
        PUCHAR                      pDataWillBeEncrypted,
        ULONG                       lengthOfData,
        PUCHAR                      pDataEncrypted,
        PULONG                      pLength
    )
{
    PANSC_ASN1_RSAPUBLICKEY         pRSA        = (PANSC_ASN1_RSAPUBLICKEY)hThisObject;
    ANSC_STATUS                     status;
    PANSC_CRYPTO_RSA_PUBLIC_KEY     pPublic;
    PANSC_CRYPTO_PUB_SSLEAY_OBJECT  pCrypto;
    PANSC_ASN1_INTEGER              pInteger;
    PANSC_CRYPTO_PUB_KEY_PARAMS     pParams;
    ANSC_CRYPTO_PUB_ALGORITHM       Alg;
    ANSC_CRYPTO_PUB_OPERATION       Op;


    if( pRSA == NULL || pDataWillBeEncrypted == NULL || pDataEncrypted == NULL || pLength == NULL)
    {
        return ANSC_ASN1_BAD_PARAMETER;
    }

    pCrypto     = (PANSC_CRYPTO_PUB_SSLEAY_OBJECT)AnscCreateCryptoPubSSLeay(NULL);

    if (pCrypto == NULL)
    {
        return ANSC_ASN1_NO_RESOURCES;
    }

    pParams = (PANSC_CRYPTO_PUB_KEY_PARAMS)AnscAllocateMemory(sizeof(ANSC_CRYPTO_PUB_KEY_PARAMS));

    if( pParams == NULL)
    {
        pCrypto->Remove(pCrypto); 

        return ANSC_ASN1_NO_RESOURCES;
    }

    pPublic    = (PANSC_CRYPTO_RSA_PUBLIC_KEY)&pParams->Key.RSA.RsaPublicKey;

    /* RSA public key */
    pInteger    = (PANSC_ASN1_INTEGER)pRSA->GetChildByIndex(pRSA,0);
    pPublic->Modulus.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->Modulus.Data, pInteger->pValueBuffer, pPublic->Modulus.Length);

    pInteger    = (PANSC_ASN1_INTEGER)pRSA->GetChildByIndex(pRSA,1);
    pPublic->PublicExponent.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->PublicExponent.Data.ucData, pInteger->pValueBuffer,pPublic->PublicExponent.Length);

    /* encrypt it */
    Op  = ANSC_CRYPTO_PUB_OPERATION_ENCRYPT;
    Alg = ANSC_CRYPTO_PUB_ALGORITHM_RSA_ENCRYPTION;
    pParams->Key.RSA.RsaPublicKey    = *pPublic;

    pParams->InputSize  = lengthOfData;
    pParams->pInput     = (PVOID)pDataWillBeEncrypted;

    pParams->OutputSize = *pLength;
    pParams->pOutput    = (PVOID)pDataEncrypted;

    status = 
        pCrypto->Request
            (
                Alg, 
                Op, 
                (ANSC_HANDLE)pParams, 
                NULL, 
                NULL
            );

    if(pLength)
    {
        *pLength = pParams->OutputSize;
    }

    pCrypto->Remove(pCrypto); 
    AnscFreeMemory(pParams);

    return status;
}

BOOLEAN
AnscAsn1RSAPublicKeyInitKey
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hKeyGenHandle
    )
{
    PANSC_ASN1_RSAPUBLICKEY         pThisObject     = (PANSC_ASN1_RSAPUBLICKEY)hThisObject;
    PANSC_CRYPTO_PUB_KEY_GEN_PARAMS pGenParams      = (PANSC_CRYPTO_PUB_KEY_GEN_PARAMS)hKeyGenHandle;
    PANSC_ASN1_INTEGER              pInteger;

    if( pThisObject == NULL || pGenParams == NULL)
    {
        return FALSE;
    }

    /* init the value one by one */
    pInteger = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject,0);
    pInteger->SetUnsignedStringValue
        (
            pInteger,
            pGenParams->PublicKey.RSA.Modulus.Data,
            pGenParams->PublicKey.RSA.Modulus.Length
        );

    pInteger = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject,1);
    pInteger->SetUnsignedStringValue
        (
            pInteger,
            pGenParams->PublicKey.RSA.PublicExponent.Data.ucData,
            pGenParams->PublicKey.RSA.PublicExponent.Length
        );

    return TRUE;
}

BOOLEAN
AnscAsn1RSAPublicKeyIsKeyMatching
    (
        ANSC_HANDLE                 hThisObject,
        PKI_KEY_TYPE                keyType,
        ANSC_HANDLE                 hKeyParams
    )
{
    PANSC_ASN1_RSAPUBLICKEY         pThisObject     = (PANSC_ASN1_RSAPUBLICKEY)hThisObject;
    PANSC_CRYPTO_PUB_KEY_GEN_PARAMS pGenParams      = (PANSC_CRYPTO_PUB_KEY_GEN_PARAMS)hKeyParams;
    PANSC_ASN1_INTEGER              pInteger;

    if( hThisObject == NULL || hKeyParams == NULL || keyType != PKI_RSA_KEY)
    {
        return FALSE;
    }

    /* check the values */
    pInteger = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject,0);

    if(!isIntegerMatching
        (
            (PUCHAR)pInteger->GetValueBuffer(pInteger),
            pInteger->uLength,
            pGenParams->PublicKey.RSA.Modulus.Data,
            pGenParams->PublicKey.RSA.Modulus.Length
        ))
    {
        return FALSE;
    }

    pInteger = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject,1);

    if( pInteger->uLength != pGenParams->PublicKey.RSA.PublicExponent.Length)
    {
        return FALSE;
    }

    if(!AnscEqualMemory
        ( 
            pInteger->GetValueBuffer(pInteger), 
            pGenParams->PublicKey.RSA.PublicExponent.Data.ucData,
            pInteger->uLength
        ))
    {
        return FALSE;
    }

    return TRUE;
}

ANSC_STATUS
AnscAsn1RSAPublicKeyExportPublicKey
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hKeyGenParams
    )
{
    PANSC_ASN1_RSAPUBLICKEY         pThisObject     = (PANSC_ASN1_RSAPUBLICKEY)hThisObject;
    PANSC_CRYPTO_PUB_KEY_GEN_PARAMS pGenParams      = (PANSC_CRYPTO_PUB_KEY_GEN_PARAMS)hKeyGenParams;
    PANSC_ASN1_INTEGER              pInteger;

    if( hThisObject == NULL || hKeyGenParams == NULL)
    {
        return ANSC_STATUS_FAILURE;
    }

    /* RSA public key */
    pInteger    = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject,0);
    pGenParams->PublicKey.RSA.Modulus.Length = pInteger->uLength;
    AnscCopyMemory
        (
            pGenParams->PublicKey.RSA.Modulus.Data, 
            pInteger->GetValueBuffer(pInteger),
            pInteger->uLength
        );

    pInteger    = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject,1);
    pGenParams->PublicKey.RSA.PublicExponent.Length = pInteger->uLength;
    AnscCopyMemory
        (
            pGenParams->PublicKey.RSA.PublicExponent.Data.ucData, 
            pInteger->GetValueBuffer(pInteger),
            pInteger->uLength
        );

    return ANSC_STATUS_SUCCESS;
}

/**********************************************************************

 OBJECT -- ANSC_ASN1_DSAPUBLICKEY

 DSAPublicKey ::= Integer 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDSAPublicKey
    (
        ANSC_HANDLE                 hReserved
    )
{
    PANSC_ASN1_DSAPUBLICKEY         pThisObject  = NULL;

    /*
     * Create the base ASN.1 object.
     */
    if( hReserved != NULL)
    {
        pThisObject = (PANSC_ASN1_DSAPUBLICKEY)
            AnscAsn1CreateInteger
                (
                    hReserved
                );
    }
    else
    {
        pThisObject = (PANSC_ASN1_DSAPUBLICKEY)
            AnscAsn1CreateInteger
                (
                    (ANSC_HANDLE)sizeof(ANSC_ASN1_DSAPUBLICKEY)
                );
    }

    if( pThisObject == NULL)
    {
        return (ANSC_HANDLE)NULL;
    }

    /*
     * Initialize the common variables and functions for this ASN.1 object.
     */
    pThisObject->SetClassName(pThisObject, "ANSC_ASN1_DSAPUBLICKEY");
    pThisObject->SetName(pThisObject, "DSAPublicKey");

    pThisObject->Create             = AnscAsn1CreateDSAPublicKey;
    pThisObject->Verify             = AnscAsn1DSAPublicKeyVerify;
    pThisObject->InitKey            = AnscAsn1DSAPublicKeyInitKey;
    pThisObject->IsKeyMatching      = AnscAsn1DSAPublicKeyIsKeyMatching;
    pThisObject->ExportPublicKey    = AnscAsn1DSAPublicKeyExportPublicKey;

    return (ANSC_HANDLE)pThisObject;
}


/*
 *  Manually added functions;
 */
ANSC_STATUS
AnscAsn1DSAPublicKeyVerify
    (
        ANSC_HANDLE                 hThisHandle,
        ANSC_HANDLE                 hParams,
        PUCHAR                      pDataSigned,
        ULONG                       lengthOfData,
        SIGNATURE_TYPE              SignatureType,
        PUCHAR                      pSignature,
        ULONG                       uLength
    )
{
    PANSC_ASN1_DSAPUBLICKEY         pDSA        = (PANSC_ASN1_DSAPUBLICKEY)hThisHandle;
    PANSC_ASN1_DSS_PARMS            pDSSParams  = (PANSC_ASN1_DSS_PARMS)hParams;
    ANSC_STATUS                     status;
    PANSC_CRYPTO_DSA_PUBLIC_KEY     pPublic;
    PANSC_CRYPTO_PUB_SSLEAY_OBJECT  pCrypto;
    PANSC_ASN1_INTEGER              pInteger;
    PANSC_CRYPTO_PUB_KEY_PARAMS     pParams;

    if( pDSA == NULL || pDSSParams == NULL)
    {
        return ANSC_ASN1_BAD_PARAMETER;
    }

    if( uLength == 0 || pSignature == NULL || pDataSigned == NULL)
    {
        return ANSC_ASN1_INVALID_SIGNATURE;
    }

    if( SignatureType != DSA_SHA1_SIGNATURE)
    {
        return ANSC_ASN1_NOT_SUPPORTED;
    }

    if( !AnscEqualString1(pDSSParams->ClassName,"ANSC_ASN1_DSS_PARMS",FALSE))
    {
        return ANSC_ASN1_NOT_SUPPORTED;
    }

    pCrypto     = (PANSC_CRYPTO_PUB_SSLEAY_OBJECT)AnscCreateCryptoPubSSLeay(NULL);

    if (pCrypto == NULL)
    {
        return ANSC_ASN1_NO_RESOURCES;
    }

    pParams = (PANSC_CRYPTO_PUB_KEY_PARAMS)AnscAllocateMemory(sizeof(ANSC_CRYPTO_PUB_KEY_PARAMS));

    if( pParams == NULL)
    {
        pCrypto->Remove(pCrypto); 

        return ANSC_ASN1_NO_RESOURCES;
    }

    pPublic    = (PANSC_CRYPTO_DSA_PUBLIC_KEY)&pParams->Key.DSA.DsaPublicKey;

    /* DSA public key */
    pInteger    = (PANSC_ASN1_INTEGER)pDSSParams->GetChildByIndex(pDSSParams,0);
    pPublic->ParamP.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->ParamP.Data.ucData, pInteger->pValueBuffer, pPublic->ParamP.Length);

    pInteger    = (PANSC_ASN1_INTEGER)pDSSParams->GetChildByIndex(pDSSParams,1);
    pPublic->ParamQ.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->ParamQ.Data.ucData, pInteger->pValueBuffer, pPublic->ParamQ.Length);

    pInteger    = (PANSC_ASN1_INTEGER)pDSSParams->GetChildByIndex(pDSSParams,2);
    pPublic->ParamG.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->ParamG.Data.ucData, pInteger->pValueBuffer, pPublic->ParamG.Length);

    pInteger    = (PANSC_ASN1_INTEGER)pDSA;
    pPublic->ParamY.Length = pInteger->uLength;
    AnscCopyMemory(pPublic->ParamY.Data.ucData, pInteger->pValueBuffer, pPublic->ParamY.Length);

    /* Verify it */
    status = 
        pCrypto->DSAHashAndVerify
             (
                0,  /* doesnot matter with DSA, only SHA1 is supported*/
                (PVOID)pDataSigned,
                lengthOfData,
                pSignature,
                uLength,
                pParams
             );

    pCrypto->Remove(pCrypto); 
    AnscFreeMemory(pParams);

    return status;
}

BOOLEAN
AnscAsn1DSAPublicKeyInitKey
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hKeyGenHandle
    )
{
    PANSC_ASN1_DSAPUBLICKEY         pThisObject     = (PANSC_ASN1_DSAPUBLICKEY)hThisObject;
    PANSC_CRYPTO_PUB_KEY_GEN_PARAMS pGenParams      = (PANSC_CRYPTO_PUB_KEY_GEN_PARAMS)hKeyGenHandle;
    PANSC_ASN1_INTEGER              pInteger;

    if( pThisObject == NULL || pGenParams == NULL)
    {
        return FALSE;
    }

    /* init the value one by one */
    pInteger = (PANSC_ASN1_INTEGER)pThisObject;

    pInteger->SetUnsignedStringValue
        (
            pInteger,
            pGenParams->PublicKey.DSA.ParamY.Data.ucData,
            pGenParams->PublicKey.DSA.ParamY.Length
        );

    return TRUE;
}

BOOLEAN
AnscAsn1DSAPublicKeyIsKeyMatching
    (
        ANSC_HANDLE                 hThisHandle,
        PKI_KEY_TYPE                keyType,
        ANSC_HANDLE                 hKeyParams
    )
{
    PANSC_ASN1_DSAPUBLICKEY         pThisObject     = (PANSC_ASN1_DSAPUBLICKEY)hThisHandle;
    PANSC_CRYPTO_PUB_KEY_GEN_PARAMS pGenParams      = (PANSC_CRYPTO_PUB_KEY_GEN_PARAMS)hKeyParams;

    if( pThisObject == NULL || hKeyParams == NULL || keyType != PKI_DSA_KEY)
    {
        return FALSE;
    }

    /* check the values */
    return
        isIntegerMatching
            (
                (PUCHAR)pThisObject->GetValueBuffer(pThisObject),
                pThisObject->uLength,
                pGenParams->PublicKey.DSA.ParamY.Data.ucData,
                pGenParams->PublicKey.DSA.ParamY.Length
            );
}

ANSC_STATUS
AnscAsn1DSAPublicKeyExportPublicKey
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hKeyGenParams
    )
{
    PANSC_ASN1_DSAPUBLICKEY         pThisObject     = (PANSC_ASN1_DSAPUBLICKEY)hThisObject;
    PANSC_CRYPTO_PUB_KEY_GEN_PARAMS pGenParams      = (PANSC_CRYPTO_PUB_KEY_GEN_PARAMS)hKeyGenParams;

    if( hThisObject == NULL || hKeyGenParams == NULL)
    {
        return ANSC_STATUS_FAILURE;
    }

    pGenParams->PublicKey.DSA.ParamY.Length = pThisObject->uLength;

    AnscCopyMemory
        (
            pGenParams->PublicKey.DSA.ParamY.Data.ucData, 
            pThisObject->pValueBuffer, 
            pThisObject->uLength
        );


    return ANSC_STATUS_SUCCESS;
}

/**********************************************************************

 OBJECT -- ANSC_ASN1_DHPUBLICKEY

 DHPublicKey ::= Integer 

 **********************************************************************/

ANSC_HANDLE 
AnscAsn1CreateDHPublicKey
    (
        ANSC_HANDLE                 hReserved
    )
{
    PANSC_ASN1_DHPUBLICKEY          pThisObject  = NULL;

    /*
     * Create the base ASN.1 object.
     */
    if( hReserved != NULL)
    {
        pThisObject = (PANSC_ASN1_DHPUBLICKEY)
            AnscAsn1CreateInteger
                (
                    hReserved
                );
    }
    else
    {
        pThisObject = (PANSC_ASN1_DHPUBLICKEY)
            AnscAsn1CreateInteger
                (
                    (ANSC_HANDLE)sizeof(ANSC_ASN1_DHPUBLICKEY)
                );
    }

    if( pThisObject == NULL)
    {
        return (ANSC_HANDLE)NULL;
    }

    /*
     * Initialize the common variables and functions for this ASN.1 object.
     */
    pThisObject->SetClassName(pThisObject, "ANSC_ASN1_DHPUBLICKEY");
    pThisObject->SetName(pThisObject, "DHPublicKey");

    pThisObject->Create             = AnscAsn1CreateDHPublicKey;
    pThisObject->InitKey            = AnscAsn1DHPublicKeyInitKey;
    pThisObject->IsKeyMatching      = AnscAsn1DHPublicKeyIsKeyMatching;

    return (ANSC_HANDLE)pThisObject;
}


/*
 *  Manually added functions;
 */

BOOLEAN
AnscAsn1DHPublicKeyInitKey
    (
        ANSC_HANDLE                 hThisObject,
        ANSC_HANDLE                 hKeyGenHandle
    )
{
    PANSC_ASN1_DSAPUBLICKEY         pThisObject     = (PANSC_ASN1_DSAPUBLICKEY)hThisObject;
    PANSC_CRYPTO_DH_PARAMETERS      pGenParams      = (PANSC_CRYPTO_DH_PARAMETERS)hKeyGenHandle;
    PANSC_ASN1_INTEGER              pInteger;

    if( pThisObject == NULL || pGenParams == NULL)
    {
        return FALSE;
    }

    /* init the value one by one */
    pInteger = (PANSC_ASN1_INTEGER)pThisObject;

    pInteger->SetUnsignedStringValue
        (
            pInteger,
            pGenParams->PublicKey.Data.ucData,
            pGenParams->PublicKey.Length
        );

    return TRUE;
}

BOOLEAN
AnscAsn1DHPublicKeyIsKeyMatching
    (
        ANSC_HANDLE                 hThisHandle,
        PKI_KEY_TYPE                keyType,
        ANSC_HANDLE                 hKeyParams
    )
{
    PANSC_ASN1_DHPUBLICKEY          pThisObject     = (PANSC_ASN1_DHPUBLICKEY)hThisHandle;
    PANSC_CRYPTO_DH_PARAMETERS      pGenParams      = (PANSC_CRYPTO_DH_PARAMETERS)hKeyParams;

    if( pThisObject == NULL || hKeyParams == NULL || keyType != PKI_DSA_KEY)
    {
        return FALSE;
    }

    /* check the values */
    return
        isIntegerMatching
            (
                (PUCHAR)pThisObject->GetValueBuffer(pThisObject),
                pThisObject->uLength,
                pGenParams->PublicKey.Data.ucData,
                pGenParams->PublicKey.Length
            );
}

/**********************************************************************

 OBJECT -- ANSC_ASN1_KEYPAIR

 KeyPair ::= Sequence 
     {
                           keyType Integer 
                            pubKey PublicKey
                            priKey PrivateKeyInfo
     }

 **********************************************************************/
ANSC_HANDLE
AnscAsn1CreateKeyPair
    (
        ANSC_HANDLE                 hReserved
    )
{
    PANSC_ASN1_KEYPAIR              pThisObject  = NULL;

    /*
     * Create the base ASN.1 object.
     */
    if( hReserved != NULL)
    {
        pThisObject = (PANSC_ASN1_KEYPAIR)
            AnscAsn1CreateSequence
                (
                    hReserved
                );
    }
    else
    {
        pThisObject = (PANSC_ASN1_KEYPAIR)
            AnscAsn1CreateSequence
                (
                    (ANSC_HANDLE)sizeof(ANSC_ASN1_KEYPAIR)
                );
    }

    if( pThisObject == NULL)
    {
        return (ANSC_HANDLE)NULL;
    }

    /*
     * Initialize the common variables and functions for this ASN.1 object.
     */
    pThisObject->SetClassName(pThisObject, "ANSC_ASN1_KEYPAIR");
    pThisObject->SetName(pThisObject, "KeyPair");

    pThisObject->Create             = AnscAsn1CreateKeyPair;
    pThisObject->CreateChildAttr    = AnscAsn1KeyPairCreateChildAttr;
    pThisObject->GetChildName       = AnscAsn1KeyPairGetChildName;
    pThisObject->CreateChildObject  = AnscAsn1KeyPairCreateChildObject;
    pThisObject->BeforeDecodingChild= AnscAsn1KeyPairBeforeDecodingChild;
    pThisObject->InitKey            = AnscAsn1KeyPairInitKey;
    pThisObject->ExportKey          = AnscAsn1KeyPairExportKey;

    pThisObject->uTotalChild        = 3;

    /*
     * Create all the children
     */
    pThisObject->CreateAllChildren(pThisObject);


    return (ANSC_HANDLE)pThisObject;
}

PANSC_ATTR_OBJECT
AnscAsn1KeyPairCreateChildAttr
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       index
    )
{
    UNREFERENCED_PARAMETER(hThisObject);
    UNREFERENCED_PARAMETER(index);
    return NULL;
}

PCHAR
AnscAsn1KeyPairGetChildName
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       index
    )
{
    UNREFERENCED_PARAMETER(hThisObject);    
    switch ( index )
    {
        case 0:

            return"keyType";

        case 1:

            return"publicKey";

        case 2:

            return "privateKeyInfo";

    }

    return "";
}

ANSC_HANDLE
AnscAsn1KeyPairCreateChildObject
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       index
    )
{
    PANSC_ASN1_OBJECT               pThisObject      = NULL;
    PANSC_ASN1_SEQUENCE             pParent          = (PANSC_ASN1_SEQUENCE)hThisObject;

    switch( index )
    {

        case 0:

            pThisObject = AnscAsn1CreateInteger(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateChildAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetChildName(pParent,index));
            }

            break;

        case 1:

            pThisObject = AnscAsn1CreatePublicKey(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateChildAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetChildName(pParent,index));
            }

            break;

        case 2:

            pThisObject = AnscAsn1CreatePrivateKeyInfo(NULL);

            if( pThisObject != NULL)
            {
                pThisObject->AddAttribute(pThisObject, pParent->CreateChildAttr(pParent,index), FALSE);
                pThisObject->SetName(pThisObject, pParent->GetChildName(pParent,index));
            }

            break;
    }

    return pThisObject;
}

ANSC_STATUS
AnscAsn1KeyPairBeforeDecodingChild
    (
        ANSC_HANDLE                 hThisObject,
        int                         index,
        PVOID*                      ppEncoding
    )
{
    UNREFERENCED_PARAMETER(ppEncoding);
    PANSC_ASN1_KEYPAIR              pThisObject  = (PANSC_ASN1_KEYPAIR)hThisObject;
    PANSC_ASN1_INTEGER              pKeyType;
    PANSC_ASN1_CHOICE               pPubKey;

    if( index == 1)
    {
        /* check the key type */
        pKeyType = (PANSC_ASN1_INTEGER)
            pThisObject->GetChildByIndex(pThisObject, 0);

        pPubKey  = (PANSC_ASN1_CHOICE)
            pThisObject->GetChildByIndex(pThisObject, 1);

        if( pKeyType->GetIntegerValue(pKeyType) == PKI_RSA_KEY)
        {
            pPubKey->SetAndCreateSelection
                (
                    pPubKey,
                    PUBLICKEY_MASK_RSAPUBLICKEY
                );
        }
        else
        {
            pPubKey->SetAndCreateSelection
                (
                    pPubKey,
                    PUBLICKEY_MASK_DSAPUBLICKEY
                );
        }
    }

    return ANSC_STATUS_SUCCESS;
}

ANSC_STATUS
AnscAsn1KeyPairInitKey
    (
        ANSC_HANDLE                 hThisObject,
        ULONG                       keyType,
        ANSC_HANDLE                 hKeyGenHandle
    )
{
    PANSC_ASN1_KEYPAIR              pThisObject   = (PANSC_ASN1_KEYPAIR)hThisObject;
    PANSC_ASN1_INTEGER              pKeyType      = NULL;
    PANSC_ASN1_PUBLICKEY            pPubKey       = NULL;
    PANSC_ASN1_PRIVATEKEYINFO       pPriKeyInfo   = NULL;
    PANSC_ASN1_RSAPUBLICKEY         pRsaKey       = NULL;
    PANSC_ASN1_DSAPUBLICKEY         pDsaKey       = NULL;

    /* set the key type */
    pKeyType = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject, 0);
    pKeyType->SetIntegerValue(pKeyType, keyType);

    /*init the public key */
    pPubKey = (PANSC_ASN1_PUBLICKEY)pThisObject->GetChildByIndex(pThisObject, 1);
    if( keyType == PKI_RSA_KEY)
    {
        pPubKey->SetAndCreateSelection
            (
                pPubKey,
                PUBLICKEY_MASK_RSAPUBLICKEY
            );

        pRsaKey = (PANSC_ASN1_RSAPUBLICKEY)pPubKey->hSelection;

        pRsaKey->InitKey(pRsaKey, hKeyGenHandle);

    }
    else if( keyType == PKI_DSA_KEY)
    {
        pPubKey->SetAndCreateSelection
            (
                pPubKey,
                PUBLICKEY_MASK_DSAPUBLICKEY
            );

        pDsaKey = (PANSC_ASN1_DSAPUBLICKEY)pPubKey->hSelection;

        pDsaKey->InitKey(pDsaKey, hKeyGenHandle);
    }
    else
    {
        AnscTrace("Unknown key type.\n");

        return ANSC_STATUS_FAILURE;
    }

    /* set the private key info */
    pPriKeyInfo = (PANSC_ASN1_PRIVATEKEYINFO)pThisObject->GetChildByIndex(pThisObject, 2);

    pPriKeyInfo->InitKey(pPriKeyInfo, keyType, hKeyGenHandle);

    return ANSC_STATUS_SUCCESS;
}

ANSC_STATUS
AnscAsn1KeyPairExportKey
    (
        ANSC_HANDLE                 hThisObject,
        PULONG                      puKeyType,
        ANSC_HANDLE                 hKeyGenHandle
    )
{
    PANSC_ASN1_KEYPAIR              pThisObject   = (PANSC_ASN1_KEYPAIR)hThisObject;
    PANSC_ASN1_INTEGER              pKeyType      = NULL;
    PANSC_ASN1_PUBLICKEY            pPubKey       = NULL;
    PANSC_ASN1_PRIVATEKEYINFO       pPriKeyInfo   = NULL;

    /* get the key type */
    pKeyType = (PANSC_ASN1_INTEGER)pThisObject->GetChildByIndex(pThisObject, 0);
    *puKeyType = pKeyType->GetIntegerValue(pKeyType);

    /*init the public key */
    pPubKey = (PANSC_ASN1_PUBLICKEY)pThisObject->GetChildByIndex(pThisObject, 1);
    pPubKey->ExportPublicKey(pPubKey, hKeyGenHandle);

    /* set the private key info */
    pPriKeyInfo = (PANSC_ASN1_PRIVATEKEYINFO)pThisObject->GetChildByIndex(pThisObject, 2);
    pPriKeyInfo->ExportKey(pPriKeyInfo, hKeyGenHandle);

    return ANSC_STATUS_SUCCESS;
}

