#!/bin/sh

start_function() {
      cd /usr/ccsp
      sh cosa_start.sh
}

stop_function() {
    killall CcspWifiSsp
    vconfig rem eth0.500
}

case $1 in
    "start")
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac
